### PR TITLE
Dev --> Staging

### LINKED ISSUE #2339: Remove "Indian Trusts Act of 1882" link
The link to the "Indian Trusts Act of 1882" at the bottom of the [Audit and Assurances page ](https://useiti.doi.gov/how-it-works/audits-and-assurances/) needs to be removed. It deals with the country of India, not tribes in the United States.

### PR DESCRIPTION
**Pull request by coreycaitlin**
[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/dev)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/dev/)

This pull request includes the following changes:

- Add federal production data for 2016 #2345 
- Fix glossary links without associated terms #2319 
- Fix broken links in "How it works" intro #2334  
- Various copyedits and link fixes #2339 #2338 #2337 #2336 #2330 #2318 
- Bug fixes and visual refinements #2283 #2299 
- Adds Docker support

/cc anything else @jamiealbrecht @ericronne ?

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@toolness If you have time, would love to get your review on this, just for safety's sake!

**Comment by toolness** [comment]
Hmm, because I'm only really familiar with #2345 and the commits I made to add Docker support, it'd be a heavy lift for me to review all of this properly, but upon a cursory examination, it seems reasonable to me!

**Comment by ericronne** [comment]
Upon exercise of my admittedly middling sleuthing skills, i found nary a glitch! 👍

**Comment by ericronne** [comment]
💥

**Pull request merged**
