### PR TITLE
Megachart bug killing spree

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1947, #1949, #1950

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/megachart-bug-killing-spree)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/megachart-bug-killing-spree/)

Changes proposed in this pull request:
- #1947 - other revenues total for oil, gas, ngl
- added build badge to [PULL_REQUEST_TEMPLATE](PULL_REQUEST_TEMPLATE.md)
- added build badge to [README](README.md) -- placement?
- #1949, #1950 - wind and sulfur revenue by type bugs
- adds horizontal scrollbar to megachart to temporary fix width problem @ericronne 

/cc @meiqimichelle

### CODE REVIEW

**Comment by gemfarmer** [comment]
@shawnbot, @meiqimichelle there are many more bugs to squash, but this might be a good time for a review, merge, and continue!

**Comment by ericronne** [comment]
@gemfarmer i don't see the horizontal scrollbar (opened it on iphone)

**Comment by meiqimichelle** [comment]
@gemfarmer I don't see a different total for Other Revenues #1947 :( I think that one needs another look. I sent `#1949, #1950 - wind and sulfur revenue by type bugs` over to Chris for review, I think those are good.

**Comment by meiqimichelle** [comment]
@gemfarmer Does this also address #1948? I think I see it on the national page. I'm not sure where else it is supposed to show up, I'll have Chris take a look at that, too.

**Comment by gemfarmer** [comment]
@meiqimichelle you can see Helium on the national page or here: https://federalist.18f.gov/preview/18F/doi-extractives-data/megachart-bug-killing-spree/explore/CO/#revenue

**Comment by gemfarmer** [comment]
For #1947, the totals are different, it is just hard to tell. I actually thought I hadn't changed anything at first, but here is the Other Revenues value:

OLD: `-$20,886,037 `
NEW: `-$20,887,881`

**Comment by meiqimichelle** [comment]
Aweeeesome! I'll triple confirm with Chris, but then probably all good then!

**Pull request merged**
