### PR TITLE
Add US gov required links to footer

### PR DESCRIPTION
**Pull request by meiqimichelle**
This is version one, for review by DOI, related to #1275 .

:sunglasses: [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/add-footer-requ-links/)

Looks like:
screenshot 2016-03-21 10 21 16

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@gemfarmer @shawnbot I don't know why all those other commits are here. Should I squash them or something?

**Comment by gemfarmer** [comment]
@meiqimichelle looks good! I like how subtle they are. :relieved:  If you don't mind, it might be a good idea to squash these. Mostly because a few of them are pretty large change sets.

**Comment by meiqimichelle** [comment]
Ok! @gemfarmer and I figured out what happened. It turns out I'm a derp and branched off of `master` instead of `dev`. Welcome to Monday morning! haha. I will close this PR and reopen another with the work off of `dev`. Thanks to @gemfarmer for helping through rebasing tho -- still learned lots and have a better idea of how to troubleshoot these things. So, DO NOT MERGE this PR.

**Comment by meiqimichelle** [comment]
Closing in favor of #1333.

**Pull request closed without merging**
