### PR TITLE
New Reconciliation summary chart

### PR DESCRIPTION
**Pull request by gemfarmer**
For #1278 .

The PR removes the old chart html and js and adds the new one based on [this mock](https://cloud.githubusercontent.com/assets/9259185/13014475/9ade8eb6-d179-11e5-85be-68c19addb193.png)

- started adding flowchart with @meiqimichelle 

@ericronne [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/reconciliation-new-summary/explore/reconciliation/)

### CODE REVIEW

**Comment by ericronne** [comment]
Awesome @gemfarmer! Just need new copy for this line @meiqimichelle ...
image

**Comment by meiqimichelle** [comment]
@ericronne @gemfarmer Do you think it still needs a sub-head now, or should we make the headings for 'threshold' and 'variance floor' glossary-clickable instead?

**Comment by ericronne** [comment]
@meiqimichelle @gemfarmer if we kept the subhead, in theory we could preserve the table column headers clickable for sorting (eventually at least)

**Comment by gemfarmer** [comment]
@ericronne @meiqimichelle I think the subhead is nice, especially if it allows the headers to be clickable.

How about something like:

> To be considered "material", a variance must exceed both the threshold and variance floor

**Comment by ericronne** [comment]
Should the subhead serve to explain that what is considered a material variance differs for various types of revenue? EG "The criteria for what is considered a material variance differs depending on the type of revenue."

Kind of wordy

**Comment by gemfarmer** [comment]
@meiqimichelle the main pain points seem to be 
- determining how long the "long" stems need to be as the dialog heights change with screen size. Haven't thought to much about how to do this with css (wouldn't be too bad with js)
- determining the horizontal location of the stems with different width bubbles. I'm thinking that the way to approach this is to probably do some math to determine where the middle of each of the 12 columns is and create a class that will create the stem and down arrow at the middle of a declared column. Might be easier to talk over our pairing session tomorrow.

**Comment by gemfarmer** [comment]
@ericronne ready for review!

@meiqimichelle I ended up adding js for that one extension line, but leaving a long string of media queries as a no-js fallback.

**Comment by gemfarmer** [comment]
I fixed the issue that was preventing the searchable by-company data from showing up.

**Pull request merged**
