### PR TITLE
Site sprucing

### PR DESCRIPTION
**Pull request by gemfarmer**
This PR does a few things:

* removes "This site is under development" and link to `whats-new/` from the top banner #1157
* addresses a scrollbar issue that Michelle was seeing in chrome and firefox on the explore filter
* rearranged the selector on the case-studies subpages. Previously, the map for the page and selector were on the bottom of all the text in mobile. I moved these to below the introduction. @meiqimichelle could you take a look and see if you think this is a good place for these?

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@gemfarmer the banner info shouldn't be removed, unless you heard otherwise. They are there to show that the site is under constant improvement, and we'll show the latest on that what's new page.

**Comment by gemfarmer** [comment]
@meiqimichelle Ok. reverted those changes. Maybe eventually the language should change slightly, to make it sound like it is being maintained and not developed?

**Comment by meiqimichelle** [comment]
@gemfarmer Yes, good point on the language. We can run that by @coreycaitlin and see what she thinks. And I checked the case studies mobile solution. I think that's perfect for now! I'm not sure if there's a better thing for the long term, but I'd rather do some site testing first anyways, and it solves the no-way-to-navigate-on-mobile problem.

**Comment by gemfarmer** [comment]
:boom: :mouse:

**Pull request merged**
