### PR TITLE
Adding state and fiscal links doc

### PR DESCRIPTION
**Pull request by nicoleslaw**
@gemfarmer This is ready for your review (for #752). Heads up on the nested `ul`s. I tried to keep them to one level.

Also, please check my nav structure. I feel like this page is okay to be one long page, but we could also divide it up into subsections by state.

### CODE REVIEW

**Comment by gemfarmer** [comment]
@nicoleslaw Ok added the list styles. I made a lot of changes relating to the list style changes that I made. 

I deleted the `nav_items` stuff. Right now that only works on the case studies pages, though given how long the page is, we probably should have a selector or a sticky navigation area to allow users to jump to a section.

**Comment by gemfarmer** [comment]
@ericronne any ideas for creating a navigation to the different subsection on this page?
https://federalist.18f.gov/preview/18F/doi-extractives-data/state-local-fiscal-content/how-it-works/governance/legal/

**Comment by ericronne** [comment]
We could try a right-side nav, a la case studies. Looks like we have 13 states, tho, so that might be pushing it. Still may be worth a try. That will help with line lengths, too.

Also we should use the bread crumbs for the header...

How It Works /
State Legal and Fiscal Information

**Comment by gemfarmer** [comment]
@ericronne @nicoleslaw 
1. I will add the breadcrumbs
2. I think we should have some sort of navigation tool with that many states. Otherwise it is just a wall of text. Possible options that I see and thoughts on them:
* Sticky nav a la case studies. _potential downside: 13 states is a lot to have on a side navigation_
* Accordion nav with top open. 
* selector a la new explore/revenues/ page. Maybe just shows one state at a time?
* combination of the accordion nav, selector. Selector opens accordion?

**Comment by ericronne** [comment]
**Sticky option 1**
Probably too long for a non-scrolling menu.
content-level page copy 5

**Sticky option 2**
Might be okay
content-level page copy 6

**Sticky option 3**
Also might be okay
explore - landing

**Comment by nicoleslaw** [comment]
Thanks, guys! Yeah, it's way long without some sort of anchor/jump links. I don't mind v3; would that also work for mobile?

**Comment by ericronne** [comment]
maybe accordion for mobile

**Comment by gemfarmer** [comment]
Alternatively, in mobile the selector could stack on top fixed?

**Comment by ericronne** [comment]
hm maybe.
guess i have some designing to do....

**Comment by usEITI** [comment]
I liked option three as well. I think there are 18 states so too much
scrolling in option 1; I don't hate option 2 because it at least allows the
user to see right away that there are only 18 states and which ones they
are.

On Fri, Nov 13, 2015 at 4:19 PM, Eric Ronne <notifications@github.com>
wrote:

> maybe accordion for mobile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/pull/782#issuecomment-156559406>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Comment by gemfarmer** [comment]
So option 3?

**Comment by meiqimichelle** [comment]
+1 for option three

**Comment by gemfarmer** [comment]
Just to be clear before I start coding this, the content area is still going to be one long scroll area, right? I could see the alternative (only one state is visible) working well.

**Comment by gemfarmer** [comment]
Because the sticky navigation area is tied up in upgrading the sticky nav code (#696). I'll add what is left over from this to that ticket.

**Pull request merged**
