### PR TITLE
Update opt-in state data

### PR DESCRIPTION
**Pull request by msecret**
Starts issue(s) #2486 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/update_optin_state_data)

 **Moved this checklist to #2486**

## Wyoming

- [x] State revenue chart [🏇 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-local-revenue) - 2016 data, but needs validation
- [x] State disbursements  [🏇 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#state-disbursements) - 2016 data, but needs validation
- [x] Content updates ([source; limited access](https://drive.google.com/drive/folders/13ZJPUWeZbUs7kFQzNEGVvUSyalwPiPLi))
- [ ] Static charts — update or remove

## Montana

- [ ] State revenue chart [🐻 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/MT/#state-local-revenue) - still showing 2014 data
- [ ] State disbursements  [🐻 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/MT/#state-disbursements) - still showing 2014 data
- [ ] Content updates ([source; limited access](https://drive.google.com/drive/folders/1pWiMDMIbSLsxv-tyRIVSiGRF8ETu9SRB)) - #2584 
- [ ] Static charts — update or remove

## Alaska

- [ ] State revenue chart [🐟 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/AK/#state-local-revenue) - showing 2015 data
- [ ] State disbursements  [🐟 PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/AK/#state-disbursements) - showing 2015 data
- [ ] Content updates ([source; limited access](https://drive.google.com/drive/folders/1siHtT_1_rz4W4supWyYkPZuCzQooAGCu)) - #2585
- [ ] Static charts — update or remove

### CODE REVIEW

**Comment by msecret** [comment]
@mentastc can you take a look at this when you get the chance? 

https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#disbursements

I wanted to see if I got the WY opt-in state data correct before moving onto other states.

**Comment by ericronne** [comment]
We'll add a chart title for these, and include the year in it …
image

**Comment by coreycaitlin** [comment]
@brentryanjohnson @ericronne @mentastc I added headers for both the State Revenue section and the State Disbursements section — they aren't quite parallel, but I think they're both relatively clear and concise. Very open to revising if you can think of something clearer/better!

**Comment by coreycaitlin** [comment]
Just added WY content updates [noted here (limited access)](https://drive.google.com/drive/folders/13ZJPUWeZbUs7kFQzNEGVvUSyalwPiPLi). Could use a proof by @brentryanjohnson before publishing!

**Comment by brentryanjohnson** [comment]
@coreycaitlin I noticed a discrepancy between the state revenue figure in the copy ($2,218,776,004) and in the data file ($2,126,209,645). I assume the data file is correct, but it's something we should look into.

**Comment by brentryanjohnson** [comment]
@ericronne Are you working on an update to the Wyoming Revenue Sustainability chart?

image


image

**Comment by brentryanjohnson** [comment]
@coreycaitlin Minor update needed under [economic impact](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_optin_state_data/explore/WY/#economic-impact):

In **2014**, annual wages from extractive industries made up about 18% (or **$1.64 billion**) of total annual wages in the state. The average annual wage for extractive-industry jobs in Wyoming in 2016 was $84,451, or almost twice the statewide average wage of $43,813.

Should be:

In **2016**, annual wages from extractive industries made up about 18% (or **$1.6 billion**) of total annual wages in the state. The average annual wage for extractive-industry jobs in Wyoming in 2016 was $84,451, or almost twice the statewide average wage of $43,813.

**Comment by coreycaitlin** [comment]
@brentryanjohnson I bet that's still last year's data file for download...

**Comment by brentryanjohnson** [comment]
@coreycaitlin I compared the body copy to the Word doc that was sent over. It looks like they're static values in the WY.md file.

```state_impact: |
    The extractive industries play an important role in Wyoming’s economy — particularly in Campbell County's Powder River Basin and in Sublette County. For more information about employment in Wyoming, the [Department of Workforce Services](http://www.wyomingworkforce.org/) has published [long-term industry and occupational projections for 2014 to 2024](http://doe.state.wy.us/lmi/projections/2016/projections_2014-2024.htm).

    Because of relatively high annual wages (compared to other industries), extractive industries contribute a greater percentage of personal income than jobs. In 2014, annual wages from extractive industries made up about 18% (or $1.64 billion) of total annual wages in the state. The average annual wage for extractive-industry jobs in Wyoming in 2016 was $84,451, or almost twice the statewide average wage of $43,813.```

**Comment by coreycaitlin** [comment]
@msecret Let's keep this PR to just WY and MT, and put AK updates in a separate PR, for the sake of length/complexity. I'll update the PR summary to include a checklist for the outstanding WY and MT work.

**Comment by ericronne** [comment]
@brentryanjohnson updated the [wyoming opt-in chart](https://github.com/18F/doi-extractives-data/pull/2570/commits/ebad430beedbf5e8bdbc2e5d347e7dc496cae7cc?short_path=7952926#diff-79529262009958054e83e616679a7348)

**Comment by coreycaitlin** [comment]
I think it's time to merge this into `dev` and track additional follow-up in separate issues/PRs. Any objections @brentryanjohnson?

**Pull request merged**
