### PR TITLE
Multiply all production figures by 1000

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1375

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/[BRANCH_NAME]/states/)

Changes proposed in this pull request:

For all production data
- natural gas: existing numbers are too big, divide by 1000
- oil: existing numbers are too small, multiply by 1000
- apply changes to `top_state_products`
- update units in top_state_products renewables section (incidental change)

/cc @shawnbot

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Yay! We should also have Chris take a look next week to make double-sure.

Waiting to merge till @shawnbot gets a chance to review, since he's cc'd.

**Comment by gemfarmer** [comment]
@coreycaitlin thanks for looking! I mostly want @shawnbot's feedback on the incidental update I made to the `top_state_products` dataset. I think they aren't causing problems, but I'm not 100% sure.

**Comment by gemfarmer** [comment]
@shawnbot ah. Good to know. I will remove it, and add it to the gitignore

**Comment by gemfarmer** [comment]
Removed data.db. Merging once tests pass

**Pull request merged**
