### PR TITLE
Update disbursements

### PR DESCRIPTION
**Pull request by msecret**
Fixes issue(s) #1772  .

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/ms-update_disbursments)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/ms-update_disbursments/explore/#federal-disbursements)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This doesn't look like it's working to me...

screen shot 2017-11-28 at 9 27 46 am

I'll take a look and see if I can troubleshoot it while you're out today.

**Comment by msecret** [comment]
OK I reverted that change, and the disbursements section is working now.

**Comment by coreycaitlin** [comment]
Looks like it's still showing 2016 data:

screen shot 2017-11-29 at 9 34 48 am

**Comment by coreycaitlin** [comment]
@mentastc @usEITI @jennmalcolm Disbursements is now working on the federal explore data page and state pages 🎉 please take a look, and let us know if you see anything wrong: https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/ms-update_disbursments/explore/#federal-disbursements

Still working on adding the data files for download. Stay tuned!

**Comment by coreycaitlin** [comment]
And the correct downloads are now on the [Downloads page](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/ms-update_disbursments/downloads/disbursements/) for review!

**Comment by coreycaitlin** [comment]
@msecret any objection to merging this now and doing final data review on dev or staging?

**Pull request merged**
