### PR TITLE
Use consistent way of including fonts

### PR DESCRIPTION
**Pull request by msecret**
Previously, the eiti font was being included in the code differently
then the rest of the fonts, causing confusion when changing build
processes. Now it's included in the same way as the other fonts,
after being generated by fontsquirrel.

Fixes issue #2360 

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/ms-fix_fonts/)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This looks fixed in the preview link, but I'm still seeing the broken icon fonts when I pull it down to run locally...
screen shot 2018-01-16 at 5 40 23 pm

**Comment by coreycaitlin** [comment]
@msecret Did we expect this to solve the icon-font problem? If not, what else should I be looking for?

**Comment by msecret** [comment]
I definitely expected to solve it (it was working locally). Good catch though, I'll have to look into it further.

**Comment by msecret** [comment]
Move this to chokidar branch

**Pull request closed without merging**
