### PR TITLE
Make reconciliation static; reorganize

### LINKED ISSUE #1752: Double-check tax data rendering on reconciliation page
Did Chevron really report $0 taxes?

pasted image at 2016_08_17 11_10 am

/cc @mentastc

### PR DESCRIPTION
**Pull request by shawnbot**
Fixes #1752 and #1831.

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/fix-reconciliation/how-it-works/reconciliation/)

Changes proposed in this pull request:
- [x] Make reconciliation data and page static, while maintaining the ability to search by company
- [x] Move material variance footnotes into their own dataset
- [x] Actually fix #1752 :trollface:
- [x] Move tooltips up into the content
- [x] Double-check that material variance footnotes are still correct (compare with [dev](https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/how-it-works/reconciliation/))

/cc @gemfarmer @coreycaitlin @meiqimichelle

### CODE REVIEW

**Comment by ericronne** [comment]
@shawnbot @coreycaitlin  how do you feel about top-aligning text, rather than centering? Feels cleaner, more scannable to me. I also messed with an "M" icon to replace the asterisk, but it would only work for material variances. So, for now?...

image

Also would need to see what other charts would be impacted by the alignment change.

**Comment by coreycaitlin** [comment]
This is SO MUCH EASIER to check.

Okay, these two seem to be flipped (based on maths): 

screen shot 2016-09-16 at 1 55 18 pm

**Comment by gemfarmer** [comment]
This good from where I'm standing, but i'll wait for @coreycaitlin to give her 👍

**Comment by coreycaitlin** [comment]
I checked all explanations and swapped the two that were off! Good to go from my end 🎉

**Comment by meiqimichelle** [comment]
This looks like this now:
screenshot 2016-09-19 08 48 35

**Comment by meiqimichelle** [comment]
@shawnbot this is ready to go but I don't want to resolve the conflict in the Makefile -- danger zone 😬 😂  Resolve and merge away!

**Pull request merged**
