### PR TITLE
2017 Montana opt-in updates

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes issue #2584 

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/mt-updates/)

Changes proposed in this pull request:

- Adds 2017 opt-in content updates from Deloitte

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
@coreycaitlin and @msecret `_states/MT.md` has the following key/value pair:

`state_revenue_year: 2014`

I haven't changed the year value in my PR, because I don't know for sure how this affects the data being pulled in. Please advise.

**Comment by coreycaitlin** [comment]
@brentryanjohnson As soon as those small things are addressed (^^ the minerals yearbook link and natural gas number), this is good to merge! Let me know if I can help move those forward at all.

**Comment by coreycaitlin** [comment]
Okay! I was able to track down the answer for the natural gas number by going to the Montana MMS [Annual Report for 2016 (PDF)](http://dnrc.mt.gov/divisions/trust/docs/minerals-management/oil-and-gas/reports/fy2016_mmb_annual_report.pdf). On page 6, I found this:

> Gas: In FY16, the average price for gas produced on State lands decreased to $1.33 from $2.54 per thousand cubic feet (mcf), representing a 47.6% decrease from FY15. Gas production remained fairly constant at 2,859,424 as compared to 2,882,344 thousand cubic feet from FY15. 

So, it looks like we just need to change the text to `2,859,424 thousand cubic feet of natural gas`.

**Comment by brentryanjohnson** [comment]
I just found the same thing!

image

**Comment by brentryanjohnson** [comment]
Gonna merge, folks!

- [X] [Correct units for natural gas production](https://github.com/18F/doi-extractives-data/pull/2609/commits/c2217d9cc94cfbc4fc541c06c3c838dfd1b0b79e)
- [X] [Change minerals yearbook link to higher level for maintainability](https://github.com/18F/doi-extractives-data/pull/2609/commits/94c5706e8260b453177e00273426dfa2e0688c73)

**Pull request merged**
