### PR TITLE
[WIP] List withheld/no data products

### LINKED ISSUE #1851: State pages: Consolidate no-data commodities into a table
### No-data commodities don't look good in bar charts! ...
image

### Could we consolidate them into a single table and place it at the end? 
Here's a design for that...
image

## Expanded view...
image

cc @meiqimichelle @coreycaitlin @gemfarmer

### PR DESCRIPTION
**Pull request by shawnbot**
### 🚧 ⚠️  Work in progress ⚠️ 🚧 

Fixes #1851.

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/list-no-data/explore/#national-federal-production-withheld)

Changes proposed in this pull request:
- Add a paragraph (not a list, as described in #1851) at the bottom of the federal production section that lists all products with no numeric production volume (withheld _or_ no data for every year in 2006-2015)
- Add back basic CSS for `<tt>` and `<pre>` elements (not used anywhere else on the site)
- **Temporarily** add a little pictogram alongside each to explain whether it has no data or withheld production for each year in the 2006-2015 range

image

### TODO
- [x] Figure out what to say/display here
- [x] Remove the pictograms and some of the template logic needed to display them

/cc @coreycaitlin @meiqimichelle @ericronne

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Okay! The full description of what we're listing is a little gnarled, but something like "there are some products for which we have no data for the years 2006-2015, either because data for all years was withheld or because there was only production for a few years, and it was withheld for those years. There was production of these products, but we can't tell you how much."

That said, here's what I'm thinking:

- "no data" is a less interesting situation, because it generally means there's nothing to report because there was no production
- we do need to mention when there was production, but the amount was withheld

Option 1: In the brackets, list years for which data was withheld, ie `[2009, 2011]` or `[all years]`

Option 2: Break it out into two paragraphs, one for the products where data was withheld all years, and 
a second for the products for which there was mostly no data and production was only withheld for a few years.

I updated the header level (since this is part of production on federal land) and added a very brief intro sentence to ground users. Happy to talk this through later today, if that's useful!

**Comment by ericronne** [comment]
@shawnbot @meiqimichelle @coreycaitlin can we do a quick hangout to discuss this design solution? I'm just now able to focus on eiti today. thx

**Comment by coreycaitlin** [comment]
Chatted with @ericronne this morning, and the original list concept is making a lot more sense to me —I like having the list of withheld products in the same framework/section/styling as the tables before it, _because_ it implies that it shows the same scope of information. That makes it possible for us to treat it more similarly, and show data that's parallel with the other tables (that is, focus on one year). And that means we can *stop* dealing with "no data" in this list, and just show what was withheld that year.

**Comment by coreycaitlin** [comment]
@shawnbot Yes, I'm all for that! It really simplifies what users need to wrap their brain around.

Otherwise, the "no data" things in this list are best described as..._products for which there was no production in this year, but there *was* production of that product in another year between 2006-2015, for which data was withheld_.

**Comment by ericronne** [comment]
I think the table could look like this, then ...
image

**Comment by coreycaitlin** [comment]
@ericronne Could we fit a glossary link for `withheld` somewhere in there?

**Comment by ericronne** [comment]
That's ^ one way it could work, but with my design, the layout wouldn't change unless you clicked

**Comment by gemfarmer** [comment]
@shawnbot this may or may not be helpful, but I noticed that the different federal production tables that are generating the different state, offshore, and national datasets are showing different products as withheld:

```
sqlite> select distinct(product) from federal_production_state_rank where volume is null;
Clay (tons)
Coal (tons)
Potash (tons)
Salt (tons)
Soda Ash (tons)
Sodium Bi-Carbonate (tons)
Quartz Crystal (tickets/pounds)
Phosphate Raw Ore (tons)
Gilsonite (tons)
sqlite> select distinct(product) from federal_local_production where volume is null;
Anhydrous Sodium Sulfate (tons)
Borax-Decahydrate (tons)
Borax-Pentahydrate (tons)
Boric Acid (tons)
Brine Barrels (bbl)
Clay (tons)
Coal (tons)
Gold (oz)
Lead Concentrate (tons)
Leonardite (tons)
Limestone (tons)
Magnesium Chloride Brine (tons)
Manure Salts (tons)
Potash (tons)
Salt (tons)
Soda Ash (tons)
Sodium Bi-Carbonate (tons)
Sodium Bisulfite (tons)
Sodium Decahydrate (tons)
Sodium Sesquicarbonate (tons)
Sulfide (tons)
Sylvite-Raw Ore (tons)
Trona Ore (tons)
Zinc Concentrate (tons)
Copper Concentrate (tons)
Wavellite (tons)
Quartz Crystal (tickets/pounds)
Gold Ore (tons)
Gold Placer (oz)
Phosphate Raw Ore (tons)
Borax-Anhydrous (tons)
Gilsonite (tons)
Silver (oz)
Coal Waste (Sub-Econ) (tons)
sqlite> sqlite> select distinct(product) from federal_national_production where volume is null;
Anhydrous Sodium Sulfate (tons)
Borax-Decahydrate (tons)
Borax-Pentahydrate (tons)
Boric Acid (tons)
Gold (oz)
Leonardite (tons)
Limestone (tons)
Magnesium Chloride Brine (tons)
Manure Salts (tons)
Sodium Bisulfite (tons)
Sodium Decahydrate (tons)
Sodium Sesquicarbonate (tons)
Sulfide (tons)
Sylvite-Raw Ore (tons)
Trona Ore (tons)
Brine Barrels (bbl)
Wavellite (tons)
Gold Ore (tons)
Gold Placer (oz)
Borax-Anhydrous (tons)
Silver (oz)
Coal Waste (Sub-Econ) (tons)
```

**Comment by ericronne** [comment]
Design, from #2008 (including including w "withheld" icon, when we have time to implement)

image

**Comment by ericronne** [comment]
Are we not implementing the visual design then?

**Pull request merged**
