### PR TITLE
2628 federal revenue data 2017

### LINKED ISSUE #2628: Data update: Add 2017 federal revenue data
Review and Update CY 2017 Data, this will include updating all the revenue visuals.

Next step: @mentastc to vet the data file, and share it here!
[federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_CY06-17.xlsx](https://github.com/18F/doi-extractives-data/files/1717351/federal_revenue_civil-penalties_other-rev_not-tied-to-lease_acct-year_CY06-17.xlsx)
[federal_revenue_offshore_acct-year_CY06-17.xlsx](https://github.com/18F/doi-extractives-data/files/1717352/federal_revenue_offshore_acct-year_CY06-17.xlsx)
[federal_revenue_onshore_acct-year_CY06-17.xlsx](https://github.com/18F/doi-extractives-data/files/1717353/federal_revenue_onshore_acct-year_CY06-17.xlsx)

### PR DESCRIPTION
**Pull request by master12**
Fixes #2628

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/2628-federal-revenue-data-2017/)

Changes proposed in this pull request:

- Updated federal revenue data for 2017
-
-

### CODE REVIEW

**Comment by jennmalcolm** [comment]
The visualization looks good to me. It looks like the fiscal year data files are updated, but not the calendar year (CY). Could we update the CY revenue data files too? @mentastc can do a data check to see if the numbers are looking good. Thanks.

**Comment by master12** [comment]
@jennmalcolm Could you tell me where you are seeing the data issues for CY?

**Comment by jennmalcolm** [comment]
On the downloads page, the FY files are updated, but the CY files are not. I'm not sure if this should happen in a separate update, but it seems like we have the CY data too, so hopefully we can get those updated too as part of this issue. 

image

**Comment by mentastc** [comment]
Looks really awesome, I see you got the text thing at the bottom right of the revenue table!!!! One thing I noticed and its something thats not up in 2016 is that Oil share doesn't appear in the revenue table, I think this is because the line want added in 2016.

One other thing I would do is add CY in front of the 2017 on the table just to be clear which data set we are using.

**Comment by master12** [comment]
@jennmalcolm Files have been uploaded for download and @mentastc created a new ticket for his other issues. Please review and we can close this ticket for this sprint.

**Pull request merged**
