### PR TITLE
Make style guide a docker container

### PR DESCRIPTION
**Pull request by msecret**
[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/docker-styleguide-command/)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Hmm, styles have gone missing again.

**Comment by msecret** [comment]
Hmm, Federalist doesn't use docker at all right? This is mysterious to me.

**Comment by coreycaitlin** [comment]
Rebased — styles are fixed! Ready to test/review.

**Comment by coreycaitlin** [comment]
@msecret Can you post instructions for testing this? How should we identify whether this is working as intended?

**Comment by jeremiak** [comment]
@coreycaitlin You should be able to do the following:
1. Check out the branch
1. `docker-compose up`
1. Visit the styleguide at http://localhost:3000/ (on a Mac)

**Comment by coreycaitlin** [comment]
Looks good to me! Thank you!

**Pull request merged**
