### PR TITLE
Added first draft of research_results.md

### PR DESCRIPTION
**Pull request by alexpandel**
@coreycaitlin & @brentryanjohnson, would love your eyes on this - feel free to make any and all changes you see fit! (addresses issue #2535)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This looks great @alexpandel! I made a few [minor edits](https://github.com/18F/doi-extractives-data/pull/2577/commits/c89c5bc0623eaf0af93b566337281b2de77c360a), but I think this structure works well.

The only other thing I heard mentioned in synthesis that _might_ be worth noting here is the question about longer time-series...what do you think about adding that to the "other" section? (If it wasn't mentioned by enough people to be worth including, I completely defer to you on that!)

**Comment by alexpandel** [comment]
👌👌👌 edits, @coreycaitlin! Hmm yeah the longer time-series one was tricky. It's probably worth mentioning (because yeah, we def heard it), but I'm not sure if there's a conclusion or recommendation we can definitely draw from it yet, since the notes on that issue don't get very deep into the "why"... @brentryanjohnson, you were in both of the interviews where that was mentioned - any thoughts or insight on this one?

**Comment by brentryanjohnson** [comment]
@alexpandel I definitely consider it worth mentioning, although I agree it is difficult to track to a deliverable. What we heard was a desire for "historic" data in order to observe trends that are only discernible by looking further back. Depending on the analysis, it may necessitate data that goes back 5 more years, or it could require 30 years back. I don't think we know enough about the trend analyses users are conducting to know for sure "how much" data would be useful.

As a side note, we do know that data is available back to 1982 on the [statistics site](https://statistics.onrr.gov/Information.aspx).

**Comment by alexpandel** [comment]
Roger @brentryanjohnson 👍 Just added a section about long-term trends - this puppy should be ready for a final review and merge if all looks good to you two!

**Pull request merged**
