### PR TITLE
Update exports data

### LINKED ISSUE #2031: Data bug: Exports are off
The exports data (both on the live site and on dev/staging) is off.

### PR DESCRIPTION
**Pull request by shawnbot**
Fixes #2031.

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/update-exports-data)

### :sunglasses: Previews
* [Connecticut](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/CT/#exports)
* [Colorado](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/CO/#exports)
* [Idaho](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/ID/#exports)
* [Texas](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/TX/#exports)
* [Utah](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/UT/#exports)
* [Washington](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/WA/#exports)
* [Wyoming](https://federalist.18f.gov/preview/18F/doi-extractives-data/update-exports-data/explore/WY/#exports)

Changes proposed in this pull request:
- [x] Update census exports data with 2012-2015 figures
- [x] Use our more "liberal" interpretation of HS6 codes to categorize oil and gas exports
- [x] Re-categorize mining exports _except_ specific precious metals (iron, copper, and gold) as "non energy minerals"
- [x] Further refine HS6 codes
- [x] Double-check state figures  with @mentastc
- [ ] ~~Update data documentation~~ --> #2097 

/cc @coreycaitlin

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Note for this data: Census has slightly different numbers on their website than they have in the downloadable file.

**Comment by gemfarmer** [comment]
@shawnbot where does this branch stand?

**Comment by meiqimichelle** [comment]
Chatted with Chris, we think we're good on the data front. Might be at the last check box now -- update data documentation @shawnbot @gemfarmer

**Comment by meiqimichelle** [comment]
@coreycaitlin and I are moving the remaining documentation task to #2097 so we can get this merged and closed -- it is our last data fixit issue!!

**Pull request merged**
