### PR TITLE
[WIP] Interaction bug mayhem

### PR DESCRIPTION
**Pull request by gemfarmer**
⚠️
[W I P] [W I P] 
 ⚠️  

Fixes issue(s) #1989, assorted interaction bugs

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/unclickable-counties)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/unclickable-counties/)

Changes proposed in this pull request
- fixes bug that allows counties with data to be clickable
- resets maps and tables when a year is switched
- fixes a bug that was preventing counties from firing the 'mouseout' event
- [x] hide sentences in the table

/cc @meiqimichelle @ericronne

### CODE REVIEW

**Comment by ericronne** [comment]
The counties don't open for me when i click them :/

**Comment by gemfarmer** [comment]
@ericronne hmm. Maybe this will be one that we will need to review as a group. More 👀 s 

cc @meiqimichelle

**Comment by ericronne** [comment]
Sure! Annnnd here's a capture of me clicking and clicking 😁 ....
tlgaj4siov

**Comment by gemfarmer** [comment]
OMG hound, I just fixed all of you!

**Pull request merged**
