### PR TITLE
Markdownify 2

### PR DESCRIPTION
**Pull request by gemfarmer**
[🌷 PREVIEW 🌷](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/)

### What haz changed:
- merged `case-studies`, `narrative` layouts into one super layout --> `content` ([ex.](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-76dde6c354dfad772de60d413fb374f8R4))
- Intro paragraphs for content pages are [demarcated with blockquotes](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-76dde6c354dfad772de60d413fb374f8R25) --> ```> paragraph```
- [embiggened case studies headers](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-76dde6c354dfad772de60d413fb374f8R25)
- added [breadcrumb capabilities](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-76dde6c354dfad772de60d413fb374f8R25) to `content` layout 
screen shot 2016-05-11 at 4 35 00 pm

- [bold --> emphasis](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-76dde6c354dfad772de60d413fb374f8R25) on downloads pages
- removed `_how-it-works/laws-and-regulations/federal-agencies.md`
- [markdown support for nested lists](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-2f6caefde67fae08d794414f1e6a1d8aR276)
- removed `_how-it-works/natural-resources/tax-expenditures.md`
- [fixed glossary list style issue](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-fe7d78ea1073401f3f5ca175f6c8a605R13)
- [fixed natural resources "steps" list bug](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-fbb1e3ee2c84fc0b6577120a7380cbf7R15)
- added more [relational styles](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-82d366972876cb5f09e8089db96d237fR14) for effortless style
- `term-end` [bug](https://github.com/18F/doi-extractives-data/pull/1380/files#diff-b75ccff136d123a795fb461956c99252L97)
- removed unused scss

### Pages to review – Preview links 👀 
- [Case Studies Landing](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/case-studies/)
- [Case Studies Subpages – ex. Kern](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/case-studies/kern/)
- [Downloads Landing](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/)
- [Downloads – Federal Rev by location](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/federal-revenue-by-location/)
- [Downloads – Federal Rev by company](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/federal-revenue-by-company/)
- [Downloads – Federal Production](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/federal-production/)
- [Downloads – Disbursements](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/disbursements/)
- [Downloads – Reconciliation](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/downloads/reconciliation/)
- [About](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/about/)
- [Report](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/about/report/)
- [What's new](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/about/whats-new/)
- [How it works – Ownership](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/ownership)
- [How it works – Production](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/production)
- [How it works – Revenues](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/revenues)
- [How it works – Federal Laws](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/federal-laws)
- [How it works – Federal Reforms](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/federal-reforms)
- [How it works – State laws and regs](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/state-laws-and-regulations)
- [How it works – State Legal fiscal info](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/state-legal-fiscal-info)
- [How it works – Tribal laws and regs](https://federalist.18f.gov/preview/18F/doi-extractives-data/markdownify-2/how-it-works/tribal-laws-and-regulations)

### CODE REVIEW

**Comment by gemfarmer** [comment]
@ericronne @coreycaitlin @meiqimichelle new layouts for content pages is ready for review. Visual and user (content editor) feedback welcome! Preview links above!

**Comment by coreycaitlin** [comment]
Okay! this is a lot of stuff. @gemfarmer, do you have time to pair with me on reviewing this, so I can get more confident about reviewing PRs?

**Comment by gemfarmer** [comment]
@coreycaitlin didn't see that, but yes!

**Comment by gemfarmer** [comment]
I added documentation for adding to content pages here: https://github.com/18F/doi-extractives-data/wiki/EITI-Flavored-Markdown

**Pull request merged**
