### PR TITLE
[WIP] State page prototype

### PR DESCRIPTION
**Pull request by shawnbot**
[:sunglasses: preview on Federalist](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/CA/)

This is a _very_ work in progress PR that adds state pages with data from our new database workflow in #1353. The goal here is to determine whether we're on the right track in our wireframing exercise, #1347. 

There's no index of all of the state pages yet, but you can see them by changing the URL, for instance with [Utah](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/UT/) and [Texas](https://federalist.18f.gov/preview/18F/doi-extractives-data/state-pages/states/TX/). Right now we've only got revenue and production on federal land, but all lands production and jobs are on the way.

### CODE REVIEW

**Comment by gemfarmer** [comment]
@shawnbot --> eee5880 adds Exports data. Not sure if we want to include more (namely rank), but this should be a start

**Comment by meiqimichelle** [comment]
@shawnbot _it begins!_ I'm excited. As for the two years -- yep, not super interesting. I remember on our beta site back in the day we did the bubble chart -- and switching between the years turned out to be a pretty big yawn because the funds don't change much year to year. The story here is not likely in the year-over-year change.

**Comment by gemfarmer** [comment]
@shawnbot didn't see this. Will run the commands and get back to you.

**Comment by gemfarmer** [comment]
@shawnbot looks great _except_ I'm running into this error: `/bin/sh: ./node_modules/.bin/tito: No such file or directory` which is preventing all the tables from being added. I'm guessing you added `tito` to bin but didn't save it??

**Comment by gemfarmer** [comment]
Did you add `nodemodules/.bin` to your `PATH`?

**Comment by gemfarmer** [comment]
@shawnbot just took another stab at this. I originally installed the dev dependencies with node v4.2.6 instead of v5.0.0, and for whatever reason it didn't add `tito` to the `node_modules/.bin` directory. I tried again using v5.0.0 and all the correct dependencies were added and the commands run perfectly. 

Here is a sample from my diff `git diff origin/state-pages _data`. Basically the only difference I saw was slight adjustment to the yml syntax. Is that what you were hoping?

screen shot 2016-04-19 at 3 22 46 pm

**Comment by gemfarmer** [comment]
@shawnbot 😍 nice! looks awesome

**Comment by gemfarmer** [comment]
Closing in favor of #1651

**Pull request closed without merging**
