### PR TITLE
Visual bug pruning

### PR DESCRIPTION
**Pull request by gemfarmer**
Addresses several bugs on #1243 

@ericronne :sunglasses: [PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/) :sunglasses: 

:house: [Homepage:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/)
- [x] See how it works blue bottom

:moneybag: [Reconciilation:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/explore/reconciliation/)
- [x] Glossary-like company filter (lower search bar) 
- [x] Center stack reconciliation left column header
- [x] Get rid of pennies on reconciliation, revenue by company, rev by location

:money_with_wings:  [Rev by location:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/explore/federal-revenue-by-location/)
- [x] Get rid of pennies on rev by location
- [x] 40px buffer between map and filter

:penguin:  [Rev by company:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/explore/federal-revenue-by-company/)
- [x] Get rid of pennies on rev by company
- [x] Bold face totals
- [x] duplicate filter bug

:construction_worker: [GDP:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/explore/gdp/)
- [x] Upper line rule off on GDP (not on exports)
- [x] Add space between columns on GDP

:ship:  [Exports:](https://federalist.18f.gov/preview/18F/doi-extractives-data/viz-bugs/explore/gdp/)
- [x] Add space between columns on exports

Redacted:
- [x] ~~Make sure all headers are over the data columns they are describing~~
- [x] ~~Reconciliation and Rev by company (add accordion)~~

Future:
- Need to address the top ribbon areas on the homepage, How it works and Explore landing pages. Perhaps add table display instead of floats

### CODE REVIEW

**Comment by ericronne** [comment]
xo @gemfarmer!

One unforeseen consequence of enlarging the chart titles is that some break onto three lines. I've created issue #1307 to address this when we have time.

My only other suggestion is to reduce the space between the new year button row and the title, sb more like this if poss...

image

**Comment by gemfarmer** [comment]
@ericronne I'll add extra padding, but hold of on additional sticky changes (for this PR) until we have a solid strategy in place. Sound good?

**Comment by ericronne** [comment]
extra padding @gemfarmer??
i'm looking for the year buttons to be closer to the chart header? sorry if i'm confusing u!

**Comment by gemfarmer** [comment]
@ericronne this is a funny one. It is actually quite hard to bring it in too much without completely mucking up the page layout. But I did get it closer.

Then:
screen shot 2016-03-07 at 12 44 44 pm

and Now:
screen shot 2016-03-07 at 12 44 37 pm

**Comment by meiqimichelle** [comment]
So many things! :mans_shoe: :bug:

**Comment by gemfarmer** [comment]
I know. I'm going to resolve these conflicts and then it should be good to merge, if @ericronne thinks it is ready.

**Comment by gemfarmer** [comment]
WAHOO!

**Comment by gemfarmer** [comment]
@meiqimichelle @ericronne can one of you two review and merge this if it is good to go?

**Pull request merged**
