### PR TITLE
Updates to top ribbon

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2201 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/visual-bugses)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/visual-bugses/)

Changes proposed in this pull request:
- improve look of top ribbons

/cc @ericronne

### CODE REVIEW

**Comment by ericronne** [comment]
Can we do a ten-minute pair? I see two minor things that could use doing:
 - [ ] Add space above the home-page blue button in the wide viewport
 - [ ] How it works spacing above the callout card is too tight in both the tablet and mobile views …

### Tablet
image

### Mobile
image

thx!

**Comment by gemfarmer** [comment]
@ericronne I think you'll love these last changes!

**Comment by ericronne** [comment]
Sooooo close!

For How it works, "The U.S. ranks …" is still crowding near the top of its div on mobile …
image

And this is no biggie if it's a pain, but i just realized that the selectors for Explore and Case studies don't left-right align with their intro text.
image

**Comment by gemfarmer** [comment]
@ericronne I took a stab at the select box issue as well 
7d6e94c

**Comment by ericronne** [comment]
Testify!

**Pull request merged**
