### PR TITLE
All commodities rollups

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1973

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/all-commodities)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/all-commodities/)

Changes proposed in this pull request:
- [x] ensure that offshore revenue rollups are accurate
- [x] ensure that national revenue rollups are accurate
- [x] ensure that state revenue rollups are accurate
- [x] ensure that it displays properly on the national page

screen shot 2016-09-20 at 10 38 06 am

/cc @meiqimichelle

### CODE REVIEW

**Comment by gemfarmer** [comment]
@meiqimichelle ready for review!

**Comment by gemfarmer** [comment]
@meiqimichelle it looks like the data tests are failing. I'm going to investigate!! Woo data tests!!!!

**Comment by gemfarmer** [comment]
@meiqimichelle a78eba0 should have updated the data to pass the tests. When it passes, merge at will!

**Comment by meiqimichelle** [comment]
🎉 🐭 💥

**Pull request merged**
