### PR TITLE
Update gdp data

### PR DESCRIPTION
**Pull request by msecret**
Fixes issues #2504, #2506 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/update_gdp_data)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/update_gdp_data/)

Changes proposed in this pull request:

- Downloaded the new data from BEA
- Updated the data on site with the data update scripts

/cc relevant people

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Huh, I'm still seeing this missing on both [national](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_gdp_data/explore/#gdp) and [state](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/update_gdp_data/explore/IL/#gdp) pages.

Looking at the updated data files, it looks like past years' data changed slightly (which often happens), but I'm not seeing new data for 2016.

**Comment by msecret** [comment]
OK national gdp seems to have 2016 now, as do states. The states.tsv file was deleted somehow?

There were still some failed requests when I ran the script, I might look into that further, but now would be a good time to check the data on site. There may be additional changes on site to make to get data to show up. I'm waiting for federalist to build

**Comment by coreycaitlin** [comment]
It looks like it works! The $ number looks good, but looking at the national % number (in conjunction with #2504) makes me think something's wonky. (That is, the national % issue might be a longer-standing bug, not a new thing.) Let's make sure to validate the $ figures **and** spot-check the % enough to figure out the scope of that bug.

**Comment by brentryanjohnson** [comment]
I'll help spot-check the data this morning. 

We should probably expedite a fix for production release because of the way the GDP percent value affects the state descriptions.

image

**Comment by mentastc** [comment]
two questions, the numbers are down a lot, are we pulling in all the data? second, the percent on the national page is 1.4% and it never changes for any of the years, is this correct? @coreycaitlin @msecret

**Comment by brentryanjohnson** [comment]
@coreycaitlin and @msecret 
I wonder if [this csv file](https://github.com/18F/doi-extractives-data/blob/dev/data/gdp/bea/gdp-by-industry.csv) has something to do with our GDP percent value issues. It's titled _Value Added by Industry as a Percentage of Gross Domestic Product_. 

It hasn't been updated since 2014, but it also seems to be locked in to the 2004 value for "mining."

image

**Comment by coreycaitlin** [comment]
@msecret In the process of fixing this, we realized that we have some apparently-unused files in the `data/gdp` folder:

- `data/gdp/bea/gdp-by-industry.csv`
- `data/gdp/bea/README.md`

(and maybe the rest of the files in the `bea` folder)

What do you think? can we remove those?

**Comment by msecret** [comment]
The only reference I see to those files is for documentation purposes in the `get-bea-data.js` script. For example, https://github.com/18F/doi-extractives-data/blob/dev/data/gdp/get-bea-data.js#L19

**Comment by coreycaitlin** [comment]
@msecret Let's do clean-up on unused files later, if possible — otherwise, does this look good to go?

**Pull request merged**
