### PR TITLE
Chart updates

### PR DESCRIPTION
**Pull request by ericronne**
Replaces outdated SVG graphs with new versions. I also updated colors, for better contrast.

View diffs like so! ...
jyhqs0r0bc

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
At some point, we should pull actuals (if available) for the  '16-'17 "projected" figures in the [Alaska revenue sustainability chart](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/er-chart-updates/img/AK_revenue_sustainability.svg).

**Comment by brentryanjohnson** [comment]
@ericronne I haven't heard back from Deloitte regarding the data discrepancies, so in the meantime, perhaps we should pull the questionable charts out of this PR into an issue marked as blocked. That way we can move forward with the charts we know are sound and track the others independently. Let me know your thoughts.

**Comment by ericronne** [comment]
sure, can do …

**Comment by ericronne** [comment]
@jeremiak i wonder if this conflict is due to the new `public/` directory?

**Pull request merged**
