### PR TITLE
Mobile sticky nav clean up

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2109

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/sticky-nav-bugs)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/sticky-nav-bugs/)

Changes proposed in this pull request:
 - [x] sticky navigation bugs
 - [x]  return to top should go to top
 - [x]  mobile sticky nav should say “Nationwide data” instead of Explore Data

cc @ericronne

### CODE REVIEW

**Comment by ericronne** [comment]
The menu doesn't stick for me on iphone. :/

**Comment by gemfarmer** [comment]
@ericronne I'm on it!

**Comment by gemfarmer** [comment]
@ericronne ready for your review!

**Comment by ericronne** [comment]
Return to top still doesn't go to the top of the page, but everything else looks 🆗  to me

**Comment by gemfarmer** [comment]
@ericronne Did you want it to go to the very top of the page?

Right now I have it so that on larger screens the sidnav "Top" returns you to the title text and in mobile the "Top" takes you to the point on the page where the mobile nav starts.

**Comment by ericronne** [comment]
Yeah i think top should go all of the way to the very top of the page, for both desktop and mobile.

**Pull request merged**
