### PR TITLE
Fixes How it works ribbon

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2150 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/bughunt)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/bughunt/)

Changes proposed in this pull request:
- Fixes visible bug on `How it works` ribbon
- Updates the `About` ribbon

/cc @ericronne

### CODE REVIEW

**Comment by gemfarmer** [comment]
Thanks, @houndci-bot 🙄

**Comment by meiqimichelle** [comment]
Eeep, I missed this one! Is it ready to roll after @ericronne review?

**Comment by ericronne** [comment]
hm maybe after a quick live tweak during our next pairing? 😬

**Comment by gemfarmer** [comment]
It built! And I made a new issue to hold the overflow! https://github.com/18F/doi-extractives-data/issues/2201

cc @ericronne

**Pull request merged**
