### PR TITLE
Restoring Lato font

### PR DESCRIPTION
**Pull request by gemfarmer**
for ticket #569
Lato font was displaying locally but not live.

* changed the directory structure
* import Lato instead of referencing it from css directory (now bundled in main.css by scss middleware)

* NOTE: extra commits mini commits was me testing my 2fa caching

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@gemfarmer This doesn't seem to be working yet when I pull down the branch locally. But I'm also not sure if you were done with this PR -- and I realized that we never told you our usual acceptance workflow! My bad.

So: if you've got a PR in play that you're working on, call it `[WIP] Title of what you're doing`. When you're ready for review, remove the `[WIP]` from the title and assign it to someone else for review.

(You'll note I didn't follow this for my latest merges, which is not great practice, but don't always follow the review process on super tiny PRs like image switch-outs or text changes.)

**Comment by gemfarmer** [comment]
@meiqimichelle is lato.css not loading or the fonts not being added for you locally? I changed the scss file so that lato is imported into main.scss, so lato.css shouldn't show up, but the styles should be there (because you have the fonts installed on your machine I guess you will have to inspect main.css).

Also, good to know on the workflow. I will make sure to do that on my following PRs. No apologies necessary on your end! You updated me quite a bit :)

**Comment by meiqimichelle** [comment]
I'm getting a 500 error on `main.css` on this branch :( I restarted the server, and I'm trying to think if there's anything else I need to build to make the change take.

**Comment by gemfarmer** [comment]
Hmmm... that is strange. There isn't anything I should be doing other than `npm start` is there? Maybe I'm not compiling it properly? If not, I will restore the font-awesome directory structure and maybe that will  get rid of your 500.

**Comment by gemfarmer** [comment]
@shawnbot thanks for the logs. I'll take a look at it and let you know if I'm still not able to replicate the error.

**Comment by gemfarmer** [comment]
@shawnbot I have taken your suggestions into consideration and 
1. Kept the relative path the same: `../fonts/lato/lato. Changing it to `fonts/lato/lato;` breaks it for me.
2. I changed the name of the lato file to `_lato.scss` 

I also removed all of the changes that I had made to font-awesome and brought the branch up to date. When you get a chance could you test if it is working locally for you? Thanks :)

**Comment by gemfarmer** [comment]
@shawnbot cool! and strange that it wouldn't even show that they were being overwritten

**Pull request merged**
