### PR TITLE
Increased contrast of map greens

### PR DESCRIPTION
**Pull request by ericronne**
Did a quick-and-dirty opacity adjustment on the black (darkening) layer. At some point, it would be good to rebuild this so colors could be spec’d individually, with hex values. This would allow for greater flexibility, and enable us to create maps and other visualizations with more than three colors.

### CODE REVIEW

**Comment by ericronne** [comment]
fjss5nqbbu

**Comment by gemfarmer** [comment]
I think the contrast looks better. When reviewing this I noticed that the colors that we are using for the bars and the selectors on the explore pages don't match any of the map colors. I thought we had it matching the middle color, but the preview at `dev` doesn't even do that. Do you remember when we strayed @ericronne ?

**Comment by ericronne** [comment]
I don't remember that being a rule, though maybe it was! The colors work, though. Was there a technical reason to match them?

**Comment by gemfarmer** [comment]
No technical reason. I just thought that maybe having fewer colors would be better. Your domain though! I like that green, so I'm not bummed.

**Comment by ericronne** [comment]
Yep i hear you. Max contrast was the goal of this change, which doesn't necessarily yield the prettiest colors.

**Pull request merged**
