### PR TITLE
How it works: Restructuring and new content

### PR DESCRIPTION
**Pull request by coreycaitlin**
This PR will gather all 2017 content additions, which require a restructuring of the "How it works" section to make space for them.

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/how-it-works)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/)

Changes proposed in this pull request:

- [x] Nonenergy minerals #2314 [💎 preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/nonenergy-minerals/)
- [x] Renewables #2333 [🌞 preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/renewables/)
- [x] Forestry #2313 [🌲 preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/forestry/)
- [x] Tribal overview #2387 [⛰ preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/#tribal-overview) - 4 pages
- [x] Life of a lease #2389 previews: [🏖 onshore](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/lease-process-onshore/) [⛵️ offshore](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/lease-process-offshore/)
- [x] Colorado opt-in content #2388 [🏔 preview](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/explore/CO/)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Most of the content is now in here and ready for review! This could use a close look-through by @brentryanjohnson, and will take a bit more clean-up (especially in the tribal overview pages). Take a look at the "How it works" page as well as the individual content pages, and please don't hesitate to make whatever edits you deem appropriate!

**Comment by coreycaitlin** [comment]
@mentastc For your review!

**Comment by mentastc** [comment]
@coreycaitlin  the formating on this page is strange, commodity headings are small font 
https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/tribal-production/

**Comment by ericronne** [comment]
Wow lots o' content! Nom. The [resources to revenue](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/#process) section of how it works still feels a little 🤔 structurally. I don't have a solution to propose, but happy to put 🤔 🤔 together!

**Comment by mentastc** [comment]
@coreycaitlin this page gets a 404 https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/tribal-ownership-and-governance/

**Comment by mentastc** [comment]
@usEITI

**Comment by brentryanjohnson** [comment]
@coreycaitlin There are 5 notes on [the production page](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/how-it-works/how-it-works/tribal-production/) related to adding links at a later date. We should track down the links or remove the notes.

**Comment by coreycaitlin** [comment]
Okay! Thanks to all who've reviewed so far 🎉 The link to the tribal ownership and governance page should be fixed now.

Remaining mini-tasks:

- [ ] Revisit notes about footnotes and cross-linking in the tribal overview
- [ ] @ericronne I would love to problem-solve that awkward structural section!
- [ ] Remaining CO links + state governance content
- [ ] CO revenue and disbursements #2485 
- [ ] Fix awkward heading hierarchy on tribal production page

**Comment by coreycaitlin** [comment]
@jamiealbrecht Can you tackle the link-creation and cleanup on the tribal pages? Let me know if you need to chat or pair on that!

**Pull request merged**
