### PR TITLE
New card images woo, also changed a link and emboldened small headers

### PR DESCRIPTION
**Pull request by ericronne**
[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/card-agains/)

### CODE REVIEW

**Comment by gemfarmer** [comment]
Holy smokes @ericronne!

**Comment by ericronne** [comment]
Trivia: replaced PNGs with SVGs, which saves 345k and looks way crispy.

**Comment by gemfarmer** [comment]
Jiminy crispets those SVGs look good. My only input would be that we should probably also delete the old card images.

**Comment by ericronne** [comment]
I believe that i *did* delete them!

**Pull request merged**
