### PR TITLE
Replaces manually curated data references with data-driven alternatives

### LINKED ISSUE #2729: Create data-driven content for tribal section
We have a few sections in which we are manually updating tribal content. For example, the [how it works summary](https://revenuedata.doi.gov/how-it-works/#tribal-overview) contains "hard-coded" data values. Same with the [opening paragraph](https://revenuedata.doi.gov/how-it-works/tribal-revenue/) of the Tribal Revenue page. 

> Natural resources are increasingly a key source of income for many Native American tribes. In FY 2016, ONRR and {{ "OST" | term }} disbursed $560.4 million to tribes and allottees.

We should consider replacing this manually curated content with data-driven content. We have the tribal disbursements value in [`_data/federal_disbursements.yml`](https://github.com/18F/doi-extractives-data/blob/dev/_data/federal_disbursements.yml), but I'm having trouble accessing that value because of the spaces in `American Indian Tribes`.

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes #2729

[:sunglasses: PREVIEW](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/tribes-data-vars/)

Changes proposed in this pull request:

- Replaces [tribal disbursements reference in "How it works" summary](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/tribes-data-vars/how-it-works/#tribal-overview) 

- Replaces disbursements data references in [tribal revenue description](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/tribes-data-vars/how-it-works/tribal-revenue/)

### CODE REVIEW

**Comment by brentryanjohnson** [comment]
I agree, @jennmalcolm. It would be ideal to round it further. 

I'm already applying the `round` filter in Jekyll, but that only rounds the cents off. I'm not sure we have a Jekyll filter in place that can round it beyond that (we do have that capability in our chart JS library).

`{{ disbursements[disbursement_year] | round | intcomma_dollar }}`

@master12 Any ideas on how we might accomplish this?

**Comment by brentryanjohnson** [comment]
@master12 and @jennmalcolm As we move forward with disbursements, we'll need to keep in mind that our data variables reference only one year for disbursements (e.g. `{{ disbursement_year }}`). This is because we currently only present [one year of disbursements data](https://github.com/18F/doi-extractives-data/blob/dev/_data/years.yml).

If we end up publishing more than one year, we'll need to update these references to pull the most recent year, as we do with other data references (e.g. `{% assign year = year_range | last | to_s | default: default_year %}`).

**Comment by master12** [comment]
There are several custom formatting utilities. We can look at those and see if one works if not we can create our own. Not a big dev effort.

**Comment by brentryanjohnson** [comment]
For now, we could use an standard liquid filter to divide the result and round it. This solution relies on the value being in millions of dollars, so it isn't ideal.

It does result in a more readable instance of the value, particularly in the summary text.

how it works tribal revenue summary

`In {{ disbursement_year }}, {{ "ONRR" | term }} and {{ "OST" | term }} disbursed {{ disbursements[disbursement_year] | divided_by: 1000000 | round | intcomma_dollar }} million to tribes and allottees.`

**Comment by jennmalcolm** [comment]
@brentryanjohnson that seems like a reasonable solution to get something merged now, so let's go forward with that. Thanks.

**Comment by brentryanjohnson** [comment]
For now, I've replaced the [How it works summary text](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/tribes-data-vars/how-it-works/#tribal-overview) with the rounded version, but I left the full version on the [Tribal revenue page description](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/tribes-data-vars/how-it-works/tribal-revenue/).

I think this works, because I assume those who link through to the page content will be interested in the full number. What do you think, @jennmalcolm?

**Pull request merged**
