### PR TITLE
Offshore revenue by type

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1770 

[:sunglasses: PREVIEW Gulf revenue](https://federalist.18f.gov/preview/18F/doi-extractives-data/revenue-by-type/offshore/gulf/#federal-revenue)

[:sunglasses: PREVIEW Utah revenue](https://federalist.18f.gov/preview/18F/doi-extractives-data/revenue-by-type/explore/UT/#federal-revenue)

Changes proposed in this pull request:
- updates offshore revenue rollup to accurately reflect 'All' data
- include `offshore_revenues_by_type.yml` in the data pipelline
- updates megachart templates for offshore _and_ onshore to consolidate all `Oil & Gas`, including NGL
- updates `eiti-bar-chart.js` to accommodate more than 2 bars
- incidentally adds `top_state_products`

/cc @meiqimichelle @shawnbot

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@gemfarmer `updates offshore revenue rollup to accurately reflect 'All' data` -- does this mean that it includes those civil penalties etc that @mentastc and Nathan were telling us about?

**Comment by meiqimichelle** [comment]
@gemfarmer In general tho, this looks good to me! Should we send it over to @mentastc to spot check some numbers?

**Comment by gemfarmer** [comment]
@meiqimichelle that is an old error. The most recent error appears to be a Rubygems server error. I just triggered a rebuild to test that hypothesis...

**Comment by meiqimichelle** [comment]
To be specific:

The all commodities total is larger than the oil and gas one in offshore:
screenshot 2016-09-07 09 07 53

It looks like we are including the civil penalties info in the all total, but not in the 'other revenues' row. We need to add that. 🎉

**Comment by gemfarmer** [comment]
@meiqimichelle I added Civil Penalties to the megachart! Check it out

**Comment by gemfarmer** [comment]
Nevermind, we are keeping `Other Products` as `Other Products`, but we still need to add Civil Penalties to the revenue megachart somewhere.

@mentastc I am not seeing Civil Penalties in the data. Where are they?

**Comment by meiqimichelle** [comment]
Let's merge this for now to get the existing changes in and continue working on civil penalties with Chris elsewhere.

**Pull request merged**
