### PR TITLE
Top ribbon

### PR DESCRIPTION
**Pull request by gemfarmer**
This PR updates the HTML/CSS for the ribbon on the top of the home, about, how-it-works landing, and explore landing pages.

[:sunglasses: Homepage](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/)

[:sunglasses: About](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/about/)

[:sunglasses: How it works](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/how-it-works/)

[:sunglasses: Explore](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/explore/)

cc @ericronne

### CODE REVIEW

**Comment by ericronne** [comment]
Nice!!

Couple notes! :p ...
 - This branch doesn't have the left-right page margin fix, right?
 - For the medium viewport, could we extend the blue backgrounds (sky and water) to the edges of the window?
 - Maybe lower the button in that view as well, approximately to vertical center

About like this...
image

xo 💃

**Comment by gemfarmer** [comment]
@ericronne 

1. This doesn't have the layout margin changes yet
2. We can, it would be much simpler to remove the background colors and borders all together on the stacked view. Would that work? If not, I can find a work around.
3. I'll lower the button. Can't promise it will be perfectly center, but better

**Comment by ericronne** [comment]
If this image represents what you're thinking, then go for it. Thx!...

image

**Comment by ericronne** [comment]
Thanksir!

If it's easy to lower the button a smidge, go for it.
If not, onward!

**Comment by gemfarmer** [comment]
@ericronne I'll lower it a smidge. I also have to get it working on the other pages.

**Comment by gemfarmer** [comment]
@ericronne I think it is looking pretty crisp now. Going to do a little refactoring, then should be good to go.

[:sunglasses: Homepage](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/)

[:sunglasses: About](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/about/)

[:sunglasses: How it works](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/how-it-works/)

[:sunglasses: Explore](https://federalist.18f.gov/preview/18F/doi-extractives-data/top-ribbon/explore/)

**Comment by meiqimichelle** [comment]
Lookin' niiiiice @gemfarmer !

**Comment by gemfarmer** [comment]
Ready for review!

**Comment by gemfarmer** [comment]
@ericronne LGTM. Waiting for your review. Should be good to merge if you like it!

**Comment by ericronne** [comment]
Awesome!

**Pull request merged**
