### PR TITLE
Add 2016 reconciliation data

### LINKED ISSUE #2152: Add 2016 report reconciliation data to site
We have another year of reconciliation data for the site. Right now, there is only [one year of data on the reconciliation page](https://useiti.doi.gov/how-it-works/reconciliation/). We need to implement the tabbed interface that [we already have on the by-company data page](https://useiti.doi.gov/how-it-works/federal-revenue-by-company/2015/#).

**Data**

- [x] Load new data (excel file in this issue). We were promised that it is exactly the same shape as last year's data, and so we shouldn't have problems pulling it in. If there are problems, we can loop back with ONRR and Deloitte.
- [x] Add tabbed interface, defaulting to newest year of data
- [x] Add year distinction to yml file that contains the explanations of variances

**Content**

- [ ] Update intro block with overview of participation
- [ ] Update overview in left column
- [x] Add explanations of variances to yml file

[2016 USEITI Reconciliation Data - 20161103.xlsx](https://github.com/18F/doi-extractives-data/files/610148/2016.USEITI.Reconciliation.Data.-.20161103.xlsx)

### PR DESCRIPTION
**Pull request by shawnbot**
Fixes #2152.

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/reconciliation-2016)

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/reconciliation-2016/how-it-works/reconciliation/)

Changes proposed in this pull request:
- [x] Add 2016 reconciliation data, and update import/transform/YAML scripts to organize reconciliation data by year
- [x] Add yearly reconciliation pages at `/how-it-works/reconciliation/201{3,6}`
- [x] Add redirect from old reconciliation URL to latest year data
- [x] Convert reconciliation years into a Jekyll collection (`_reconciliation/{year}.md`)
- [x] Add tab navigation to switch between years
- [x] Update sidebar text (`introduction` front matter) for 2016 to make sense
- [ ] ~~Update links from `/how-it-works/reconciliation/` to `/how-it-works/reconciliation/2016/`~~

I started down the road of making the reconciliation results list items for each page dynamic, but then realized that I wasn't looking at the right things. I gave up on that and copied the stats from the 2016 executive summary.

/cc @meiqimichelle @usEITI

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@shawnbot I think the 2016 reconciliation report looked at 2015 data, not 2016 data, so that...

- 2015 report -- 2013 data
- 2016 report -- 2015 data

And how do you want me to edit the reconciliation explanations? Should I just pull down this branch and work with the `yml` file?

**Comment by gemfarmer** [comment]
Do we want to change URLs that currently direct to `/how-it-works/reconciliation/` to `/how-it-works/reconciliation/2016/` instead? So that we don't have to rely on the redirect

**Comment by gemfarmer** [comment]
Places that might require changes:
- https://github.com/18F/doi-extractives-data/blob/de55e96f3442faa6556ee18c8719d118321110f0/_explore/revenue/reconciliation.html#L4
- https://github.com/18F/doi-extractives-data/blob/842b9c54646bd7c3b891a65b8a30bc0d57c85b4e/data/reconciliation/README.md#L3
- https://github.com/18F/doi-extractives-data/blob/e066e8d1f5fa4a27483f02604844ef9b97672f4a/_how-it-works/default.md#L136:L138
- https://github.com/18F/doi-extractives-data/blob/e066e8d1f5fa4a27483f02604844ef9b97672f4a/pages/whats_new.md#L30
- https://github.com/18F/doi-extractives-data/blob/e066e8d1f5fa4a27483f02604844ef9b97672f4a/pages/whats_new.md#L42
- https://github.com/18F/doi-extractives-data/blob/b9042a10f4e657506eb13efe9ed7721bb09d3807/pages/about.html#L75

**Comment by meiqimichelle** [comment]
I don't love the look of the redirect, but that does seem more maintainable in the long run. Let's see how @coreycaitlin feels about it as she goes through to update the content on those pages.

**Comment by coreycaitlin** [comment]
Yeah, that redirect isn't gorgeous. More importantly, we should sort out the year inconsistency, where we use `2013` as shorthand for the 2015 report (which uses 2013 data), and `2016` for the 2016 report (which used 2015 data). (Does your head hurt yet?)

**Comment by meiqimichelle** [comment]
I added an issue (#2180) for the data documentation task. In the meantime, I added the excel for the 2016 report data for download and edited the intro on the documentation page to make things a little clearer.

**Comment by meiqimichelle** [comment]
🎉 🐭 💥 🚢

**Pull request merged**
