### PR TITLE
Adds subnavigation items for disbursements subheadings

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes issue #

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/explore-subnav/)

Changes proposed in this pull request:

- We're missing [subnavigation items for Disbursements](https://revenuedata.doi.gov/explore/#federal-disbursements). Other sections have subnav items for `h3`s.
- Adds subnavigation items for Disbursements section of explore data

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Hm, good catch on the inconsistency. The two fund detail sections _could_ also be downgraded to h4s. Which approach do you think makes more sense?

**Comment by brentryanjohnson** [comment]
In terms of hierarchy, LWCF and HPF are both subordinate to "Disbursements by fund," so downgrading makes sense. I'll recommit.

**Comment by coreycaitlin** [comment]
@brentryanjohnson This looks good to me! Is this still a WIP, or are we good to merge?

**Comment by brentryanjohnson** [comment]
@coreycaitlin I remove the WIP status. Let's merge!

**Pull request merged**
