### PR TITLE
Code: How it works landing Stub

### PR DESCRIPTION
**Pull request by gemfarmer**
Addresses #730 by way of designs @ #729.

This PR stubs out the new How it Works landing page.

See it live here: https://federalist.18f.gov/preview/18F/doi-extractives-data/how-it-works-landing/how-it-works/

A few thoughts/questions/notes:
*  Since we are unsure what to put in the top banner, maybe we could emulate the Explore Data landing top area? A ribbon with smaller header text and a breadcrumb? Thoughts @ericronne ?
* I changed the indentation on the Explore Data landing section. Keep?
* I made three new pages: `/how-it-works/ownership/`, `/how-it-works/production/`, `/how-it-works/revenues/` based on the updated IA. @nicoleslaw does that work for you, or do you want a different page structure?
* I didn't touch the governance sections, though the new federal, state, tribal breakdown doesn't really mesh with the current page structure.

@meiqimichelle @shawnbot

### CODE REVIEW

**Comment by gemfarmer** [comment]
@ericronne @nicoleslaw  thoughts on the state of this PR? Is it mergeable?

**Comment by nicoleslaw** [comment]
I'm good with the governance structure for now. I think we'll need a few other pages under /governance/, but I want to check in with @meiqimichelle tomorrow on the IA.

**Comment by meiqimichelle** [comment]
*  Since we are unsure what to put in the top banner, maybe we could emulate the Explore Data landing top area? A ribbon with smaller header text and a breadcrumb?
_Yep! I think this is good for now._

* I changed the indentation on the Explore Data landing section. Keep?
_I'm not sure about this, but we can change indentation in visual bug fixes later. It doesn't need to block the merge._

* I made three new pages: `/how-it-works/ownership/`, `/how-it-works/production/`, `/how-it-works/revenues/` based on the updated IA.
_Yep! And I just added urls to the IA and tracked that work in #794. Yay._

* I didn't touch the governance sections, though the new federal, state, tribal breakdown doesn't really mesh with the current page structure.
_Take a look at those new IA updates. Hopefully they answer the question of what these sections should stub to. I'm assigning this back to you for this bullet point._

**Comment by gemfarmer** [comment]
@meiqimichelle Awesome I'll on the urls in line.

**Comment by gemfarmer** [comment]
@meiqimichelle I have added the new governance sections as page subs and migrated the content from `governance/legal/` to `governance/state-laws-and-regulations/` I left the current governance page and `governance/taxes/` for reference and because I wasn't sure where to put it.

Once the hound PR is merged, I'm going to rebase and then this should be good to review/merge.

**Comment by gemfarmer** [comment]
@meiqimichelle @nicoleslaw This should be good for another review.

https://federalist.18f.gov/preview/18F/doi-extractives-data/how-it-works-landing/how-it-works/

I have added the new governance sections as page subs and migrated the content from governance/legal/ to governance/state-laws-and-regulations/ I left the current governance page and governance/taxes/ for reference and because I wasn't sure where to put it.

**Pull request merged**
