### PR TITLE
First wave bug hunt 

### PR DESCRIPTION
**Pull request by gemfarmer**
For #944, #976, #986 , #892

* Fixes the explore description bug
* fixes the tagging issue on search results
* fix show/hide explore toggle
* fixed GDP and exports radio buttons

@meiqimichelle ready for review

### CODE REVIEW

**Comment by gemfarmer** [comment]
@meiqimichelle ready for review!

**Comment by gemfarmer** [comment]
@meiqimichelle I added/fixed the radio button in exports and gdp, but added more JS than I would have like to because I had to manage the 'checked' property. @shawnbot, could you review my changes? I realized post that the radio field is different/convoluted enough to warrant a 'eiti-radio' component. For now, maybe just make sure it isn't complete spaghetti?

**Comment by meiqimichelle** [comment]
@gemfarmer There are still some bugs here:
- The sentence doesn't seem to be updating properly anymore -- it doesn't interact when the filter is open. (Arizona is selected here, but it still says 'entire US when the filters are open) (it updates to the correct sentence when you close the filters).
- If you're on GDP or Exports and select a region, the $/% toggle stops displaying correctly -- you get both 'selected'.

Picture for both of these:
screenshot 2015-12-07 21 29 59

**Comment by gemfarmer** [comment]
:hankey: ! Ok. Back to the drawing board!

**Comment by gemfarmer** [comment]
@meiqimichelle those bugs looked bad, but fortunately they weren't! It is ready for another review. Hopefully there's nothing else!

**Comment by meiqimichelle** [comment]
So close! Those are fixed, but now the sentence doesn't show up in the default view when you first load the page:

screenshot 2015-12-08 10 44 13

**Comment by gemfarmer** [comment]
Blurg. Hahah not a big deal. I had actually made that change, but forgot to push the changes apparently. :/

**Pull request merged**
