### PR TITLE
Close glossary by clicking anywhere

### LINKED ISSUE #819: Enhancement: where to click to close the glossary drawer
- [x] clicking outside the glossary drawer should close the glossary

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes #819 

[<3 PREVIEW <3](https://federalist.18f.gov/preview/18F/doi-extractives-data/glossary-close/)

This PR makes it so that you can close the glossary by clicking anywhere outside of the glossary _except_ on a glossary term, which will instead keep the glossary open and filter it to that term definition.

Ready for review/testing. --> @meiqimichelle :tada:

### CODE REVIEW

**Comment by gemfarmer** [comment]
new issues:

- [ ] glossary accordion displaying poorly in certain browsers
- [ ] should close when clicking a term reference.

**Comment by gemfarmer** [comment]
@meiqimichelle was the issue with the accordion looking strange in other browsers resolved?

**Comment by meiqimichelle** [comment]
@gemfarmer It was done on my machine....and I then I see I never committed anything, and my computer restarted, and wut happened?! Grumble. Let me get on that now and feel like I've done something with my day ;)

**Comment by meiqimichelle** [comment]
Um, it seems to be working now @gemfarmer. I'm gonna merge, and the re-test in `dev`. I'll do a separate PR if there's still a problem. _so strange_

**Pull request merged**
