### PR TITLE
Bug hunt, part 1

### PR DESCRIPTION
**Pull request by gemfarmer**
I'm working with @ericronne  to tackle a lot of the smaller visual bugs on the site.

### [> Preview Link <](https://federalist.18f.gov/preview/18F/doi-extractives-data/eric-and-brians-big-bad-bughunt-o-rama/) 

For some of #1229 

Changes:

* [x] select icon
* [x] search bar text verticality
* [x] spacing on top of pages for all non-banner pages
* [x] realign and resize images on about
* [x] `itital` typo

### CODE REVIEW

**Comment by ericronne** [comment]
@gemfarmer Could we test the #CCC map-color tweak to see how it looks, before locking in that change?

**Comment by gemfarmer** [comment]
@ericronne we can test the map color tweak, but it will be on a different PR. Could you take a look at the preview to see if the changes in the checklist above are to your liking?

**Comment by ericronne** [comment]
@gemfarmer, a few q's (sry!) ...
- The select icon is pretty thick, could it more closely approximate the layout below? (Can stay the same color i think)

image

- Search bar text looks like it's still one tiny pixel too low
- The images on About seem to be in the same position as before (no resizing is needed, they should stay the size they are)
- Also i think you can go ahead and push the blue-banner content down by 20 pixels (home, about, how it works, explore main pp), but i'll make a sep issue and fold this into the blue tweak i mentioned. That should be resolved today. thx!

**Comment by gemfarmer** [comment]
@ericronne Ok. I'll revisit these asap.

**Comment by gemfarmer** [comment]
Is this acceptable? Otherwise there doesn't seem to be a medium thickness chevron in [this gDrive folder](https://drive.google.com/drive/folders/0BwWYNZcEDfwaOVdIdTFxZTNNLWM)
screen shot 2016-01-27 at 12 21 11 pm

**Comment by ericronne** [comment]
Hm try this new one?
https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwabWxMZGNVMFRwN00/view?usp=sharing

**Comment by ericronne** [comment]
and a [rotated version] (https://drive.google.com/a/gsa.gov/file/d/0BwWYNZcEDfwaaHBFSEthSFdzZm8/view?usp=sharing)

**Comment by gemfarmer** [comment]
@ericronne good to merge? :rocket:

**Pull request merged**
