### PR TITLE
Add 2014 + 2015 company revenue data, year toggle

### PR DESCRIPTION
**Pull request by shawnbot**
[:sunglasses: preview on Federalist](https://federalist.18f.gov/preview/18F/doi-extractives-data/company-data/explore/federal-revenue-by-company/)

This PR adds 2014 and 2015 company revenue data and a new year toggle at the top of each annual company revenue data page. These pages are now a separate [Jekyll collection](http://jekyllrb.com/docs/collections/) with their own layout. The old URL now redirects to the 2015 data (you can test this behavior by clicking on the preview link above), and the links on the [explore data page](https://federalist.18f.gov/preview/18F/doi-extractives-data/company-data/explore/) point to 2015 with updated copy. To wrap this up, we need:

- [x] sign-off from @mentastc

### CODE REVIEW

**Comment by mentastc** [comment]
I believe it should go to the newest data set available, so 2015 (when we have it)

**Comment by meiqimichelle** [comment]
I think it makes sense to update the copy and links to the most recent year we have -- I think that's what we default to on all the other pages, yes? So, once we get 2015, we should link to 2015.

**Comment by mentastc** [comment]
I have PR'd and it looks good. looking forward to the W lines and seeing how you handle that.

**Comment by gemfarmer** [comment]
@shawnbot the accordion markup was in there for mobile views.

**Comment by gemfarmer** [comment]
haha `offending commit` :smiling_imp:

**Comment by gemfarmer** [comment]
:boom: :boom: :bomb:

**Comment by gemfarmer** [comment]
haha I have done that more than I'd care to admit

**Pull request merged**
