### PR TITLE
Change the revenue years for both optin states

### PR DESCRIPTION
**Pull request by msecret**
Fixes issue #2486 

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/ms-opt_in_data/)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
This seems like a good indicator of why AK, at least, isn't working: https://github.com/18F/doi-extractives-data/tree/dev/_data/opt_in_state_revenues

**Comment by coreycaitlin** [comment]
Huzzah! Changing the year in the state markdown file successfully fixed MT (because the data was there, it just wasn't looking for the right year). It didn't fix AK because the 2016 data isn't there yet for AK. This is great because it means this is working pretty predictably.

**Comment by coreycaitlin** [comment]
🎉 👍 🥇 Alaska is working!!!

**Comment by brentryanjohnson** [comment]
Upon reviewing this PR, I noticed the county choropleths are no longer mapping their respective values properly.

Alaska map comparison between this branch and production site

This doesn't appear to be related to this PR, as I noticed it's a problem in dev, too. @coreycaitlin and @msecret should we open a new issue for this one, or try to take care of it in this PR?

**Comment by coreycaitlin** [comment]
@brentryanjohnson If the maps are broken in `dev` too, let's treat that as a separate bug and PR. One of the ways we can keep things more predictable is by keeping PRs smaller and avoiding long-running unmerged branches.

**Pull request merged**
