### PR TITLE
Words, apostrophes, tables, etc.

### PR DESCRIPTION
**Pull request by coreycaitlin**
Fixes issue(s) #1920, #1935, #1961 and adds a `withheld` definition, per #1560 

[:dancer: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/wordy-bugs/)

Changes proposed in this pull request:

- definition for "withheld"
- fix some anchor links and an awkward widowed word on the How it Works landing page
- removes the one-row table in state disbursements sections and replaces it with a very brief list when relevant (see AK, UT, and IA for the three states possible in this section)
- removes "land" from the first 2/3 of the land-ownership legend because it's still clear what's happening there
- fixes some errant incorrect apostrophes in non-markdown content chunks

/cc @ericronne @meiqimichelle

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Tacked on these changes:

- makes the state-selector dropdown on the Explore landing page more consistent with the homepage, which also resolves the problem where we couldn't get to Alaska
- addresses concerns from the online advisory group that the wording in the Explore intro was implying a narrower scope (i.e. only federal land)
- changes default bold weight to `$weight-book` (I *think* this wasn't addressed elsewhere; sorry if I duplicated work here! I also checked quite a few pages and it looks like this change doesn't do anything weird/unexpected elsewhere)

**Comment by coreycaitlin** [comment]
2 more things!

- changes "Accounting standards" to "Audits and assurances" on the How it Works landing page, thanks to feedback from the online advisory group
- adds a definition for "mineral acres"

**Comment by ericronne** [comment]
Good stuff! The "land" redundancy in the ownership map legend may actually be helpful on the home page and explore main pages, since those maps aren't titled "Land ownership." Agree? Sorry for the confusion on that.

**Comment by ericronne** [comment]
Oh also the title of the page "Audits and assurances" links to is still "Oversight." Should we change for consistency?

There are other such issues on that page, i can help debug

**Comment by coreycaitlin** [comment]
@ericronne the land ownership map legend on the home/explore pages and the state pages is driven by the same file, so changing it once changes it both places.

**Comment by ericronne** [comment]
Wondered if that was the case. If it's easy to make an exception for these two big maps, how do you feel about that?
cc @gemfarmer

**Comment by coreycaitlin** [comment]
@ericronne No objections from me, but I think it would have to go in @gemfarmer's list of things. Which do you want me to leave it at for now?

**Comment by ericronne** [comment]
Let's stick with verbose for now (clarity ftw), and deal with the whole thing in one swoop when @gemfarmer gets the time. I'll make a new issue for that.

**Pull request merged**
