### PR TITLE
Content bugs

### PR DESCRIPTION
**Pull request by nicoleslaw**
Made initial copyedits to the diving graphics pages. I will most likely do a second pass once these changes are in dev as some of them are experiments.

### CODE REVIEW

**Comment by gemfarmer** [comment]
@nicoleslaw these changes look great. One thing to note – the 'involved' sections don't have final content in them. When adding the final content, I will try to be cognizant of the changes that you made to reduce the number of copy edits that you will need to double up on.

**Comment by gemfarmer** [comment]
Also, still waiting to get the nod from @Isabelle1512 before merging this PR.

**Comment by meiqimichelle** [comment]
@gemfarmer :  Maybe @nicoleslaw should put the 'how to get involved' content in directly from the latest text? That way she can edit in text and copy into the page -- might be more efficient.

As for @Isabelle1512 review, I will try our trick -- which is changing the `default` in Federalist to this branch, or dev, so she can see them without logging in. Plz hold....

**Comment by meiqimichelle** [comment]
Ok! The trick worked and these edits can be seen on a public url....but looking at this comment chain, I'm not sure its ready for @Isabelle1512 's review yet. @nicoleslaw , do you want content review from Isabelle now, or wait until your next pass? If you want to wait, I did a quick peek to make sure nothing looked broken -- nothing does look broken -- so feel free to hit the merge button and continue with your work!

**Comment by nicoleslaw** [comment]
@gemfarmer I'm happy to input the new get involved text when we get it (and any other text changes). Thanks for checking.

@meiqimichelle @Isabelle1512 Feel free to review the changes I made; I will be doing the same to make sure the shorter links, etc. work in practice.

**Comment by Isabelle1512** [comment]
@nicoleslaw: which url should I use to see everything? Sorry - lost on the internet!

**Comment by Isabelle1512** [comment]
@nicoleslaw: do you just want me to look at the links at the top of this thread? I'll start there...

**Comment by nicoleslaw** [comment]
Sweet, here's the link: https://federalist.18f.gov/preview/18F/doi-extractives-data/dev/resource_revenues/ I will recheck the hyphenated one; it depends on the rest of the phrase.

**Pull request merged**
