### PR TITLE
Improve docker

### LINKED ISSUE #2619: New contributor documentation does not explain how to install dependencies with Docker
Docker is great and helps us get our language level (Ruby and JS) dependencies set up, but it does currently install the respective project dependencies for those languages. This results in weird errors when trying to run the development environment with Docker, such as `webpack not found in PATH`.

Either the documentation should explain how to resolve this, or the docker build process should take care of it. I vote for the latter so that users don't need to be aware of this if they identify as less technical.

### PR DESCRIPTION
**Pull request by jeremiak**
Fixes #2619

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/improve-docker/)

Changes proposed in this pull request:

- Have docker install our ruby and javascript dependencies for us
- Remove update scripts as they are no longer needed
- Updated docs to account for this change

To test this you should be able to remove all your docker images related to the project and then follow the instructions in CONTRIBUTING.md to get the app up and going with two commands:

```
$ docker-compose build
$ docker-compose up
```

Before running those commands on your dev boxes, I've found it best to run:

```
$ docker-compose down
$ docker system prune
```

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@jeremiak I ran into the following error when I ran `docker-compose up`:

```
ERROR: for doiextractivesdata_webpack_1  Cannot start service webpack: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"webpack\": executable file not found in $PATH": unknown

ERROR: for webpack  Cannot start service webpack: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"webpack\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by brentryanjohnson** [comment]
@jeremiak I hit the same error as @coreycaitlin

**Comment by jeremiak** [comment]
@coreycaitlin - I updated the docs to include these new troubleshooting steps. I think this is ready for review/merge.

**Comment by coreycaitlin** [comment]
Just tested — looks good to me!

**Comment by coreycaitlin** [comment]
@jeremiak What do you think? Is this an improvement on the build process currently in `dev`? If so, let's merge and continue improvement in a new PR.

**Pull request merged**
