### PR TITLE
Mobile sticky nav

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #2084 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/mobile_nav)

[:sunglasses: PREVIEW national](https://federalist.18f.gov/preview/18F/doi-extractives-data/mobile-nav/explore/)
[:mountain: PREVIEW opt-in state (MT)](https://federalist.18f.gov/preview/18F/doi-extractives-data/mobile-nav/explore/MT/)
[:mountain_snow: PREVIEW non-opt-in state (UT)](https://federalist.18f.gov/preview/18F/doi-extractives-data/mobile-nav/explore/UT/)
[:ocean: PREVIEW offshore region](https://federalist.18f.gov/preview/18F/doi-extractives-data/mobile-nav/explore/offshore-gulf/)

Changes proposed in this pull request:
- added a sticky navigation for mobile
- updated header hierarchy to make all nav items sticky

/cc @ericronne @meiqimichelle

### CODE REVIEW

**Comment by meiqimichelle** [comment]
Oh wow, this is looking really good! I'll leave @ericronne to do final review tho.

**Comment by meiqimichelle** [comment]
Awwww Firefox: 
screenshot 2016-10-18 13 40 40

**Comment by ericronne** [comment]
Li'l bug on explore main...
image

**Comment by gemfarmer** [comment]
Hmm yeah there is still some funky stuff with that starting point :( and boo Firefox. You will be the death of me!

**Comment by ericronne** [comment]
bada- 💥

**Comment by gemfarmer** [comment]
The rest of this will be taken care of in #2092 !

**Pull request merged**
