### PR TITLE
[WIP] Update Federal Revenue by Company data

### PR DESCRIPTION
**Pull request by shawnbot**
[:eyes: Preview on Federalist](https://federalist.18f.gov/preview/18F/doi-extractives-data/company-data/explore/federal-revenue-by-company/)

This adds the 2014 data for Federal Revenue by Company in #1268. TODO:

- [x] Resolve styling for the year tabs. Help us, @ericronne!

- [ ] Turn company revenue years into a collection?

  Right now the company revenue years (2013 and 2014 for now, but presumably a longer list in the future) live in `site.company_revenue_years` as defined in the `_config.yml`, but this is not the right place for them. They should live in a separate Jekyll collection, which takes them out of the `_explore` directory but makes it easier to add years in the future.

- [ ] Address withheld figures:

  From what I can tell, there weren't any withheld figures in the previous data set, so we never bothered to accommodate them. There _are_ withheld figures in the new data, so as a stopgap measure I've excluded them from the data that the site uses. Let me know if we need to show the withheld figures on the site and we'll figure out how to do that correctly.

### CODE REVIEW

**Comment by ericronne** [comment]
@shawnbot et al, something like this?

image

**Comment by ericronne** [comment]
(Still messing with other design options fyi...)

**Comment by gemfarmer** [comment]
@ericronne definitely less obtrusive than a set of tabs.

**Comment by ericronne** [comment]
I really like the look of that, but it looks kind of like a slider (mostly because we have numbers as the labels). Also it can't extend beyond two, so we would have to design something different if we wanted to offer more years down the road. Here are some options. I lean toward **C** …

image

**Comment by ericronne** [comment]
Let's go with B, if all agree

**Comment by meiqimichelle** [comment]
:+1:

**Pull request closed without merging**
