### PR TITLE
Map tooltips

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1520 

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/map-tooltips/explore/)

Changes proposed in this pull request:
- adds an `eiti-tooltip` component to be used in conjunction with the `<title>` element

`eiti-tooltip` can be used like so: `<title is="eiti-tooltip">` and supports `desc` and `alt` attributes.

`desc`: text to be displayed
`alt`: applied to the `aria-label` attribute on the tooltip

Enhancement possibility: make tooltips clickable. Add `href` attribute support

/cc @shawnbot  @ericronne

### CODE REVIEW

**Comment by meiqimichelle** [comment]
The tooltips aren't working in Ffx. Pulled that out into the existing Ffx bug issue because it might be the same thing. #1748 .

**Comment by gemfarmer** [comment]
@shawnbot @ericronne @meiqimichelle now works on 🔥 🐺

**Comment by gemfarmer** [comment]
Also, the hound warnings are old. The grievances it is voicing are not real.

**Comment by meiqimichelle** [comment]
😄 I will review once Federalist builds! 🎉

**Pull request merged**
