### PR TITLE
Adds final version of 2017 Executive Summary

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Fixes issue(s) #2490 

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/executive-summary-final)

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/executive-summary-final/)

Changes proposed in this pull request:

- Adds (final) [2017 Executive Summary](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/executive-summary-final/downloads/NRRD_executive-summary-2017.pdf)
- Adds content to [report page](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/executive-summary-final/about/report/) for 2017 Executive Summary
- Adds [about page timeline](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/executive-summary-final/about/#timeline) update for 2017 Executive Summary
- Changes [homepage card](https://federalist-proxy.app.cloud.gov/preview/18f/doi-extractives-data/executive-summary-final/about/report/) to reflect addition of 2017 Executive Summary

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@mentastc Could you confirm that this is the final-final version of the executive summary, and 🆗 to publish?

**Comment by brentryanjohnson** [comment]
I've added a [commit](https://github.com/18F/doi-extractives-data/pull/2534/commits/aa045c52e3bf9aae8a47e833da3a5cfaae8f9c56) with the 12/15 update to the executive summary. I changed the file name slightly to keep track and be more consistent with past file name formats.

Please review @mentastc and @coreycaitlin.

**Comment by brentryanjohnson** [comment]
My [latest commit](https://github.com/18F/doi-extractives-data/pull/2534/commits/0d295f395342228bbeb0fec6990bb67dea3d5a9c) removes the list item highlighting state-level UDR updates from the Executive Summary. State-level UDR is currently blocked.

**Comment by coreycaitlin** [comment]
This looks good to go! Merging!

**Pull request merged**
