### PR TITLE
Feature jobs by commodity

### LINKED ISSUE #2156: Add jobs data by commodity
We don't have jobs data by commodity at the county level, but we *do* have it at the state level. We could consider showing state-level jobs data by commodity in addition to general extractives jobs by county.

### PR DESCRIPTION
**Pull request by shawnbot**
Fixes #2156.

[CircleCI](https://circleci.com/gh/18F/doi-extractives-data/tree/feature-jobs-by-commodity)

### [:sunglasses: Previews](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/)
* [National wage & salary jobs by commodity](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/explore/#employment)
* State jobs by commodity in [California](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/explore/CA/#employment), [Wyoming](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/explore/WY/#employment), [Montana](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/explore/MT/#employment), and [Utah](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/feature-jobs-by-commodity/explore/UT/#employment)

Changes proposed in this pull request:
- [x] Update (wage and salary) jobs data and load scripts to group by commodity at national, state, and county level
- [x] Create new YAML data sources for jobs by commodity
- [x] Update state and national page templates to show bar charts by commodity
- [ ] Test and validate new data

/cc @gemfarmer @coreycaitlin

### CODE REVIEW

**Comment by coreycaitlin** [comment]
Fine-tuning the NAICS code mapping, and making sure we cover all the parts of 21, here's what we came up with:

- Oil & gas - 211
    + oil and gas extraction
- Coal - 2121
    + coal extraction
- Nonenergy minerals - 2122 + 2123
    + nonenergy mineral extraction
- Mining support - 213
    + mining support
- Solar - 221114
    + solar energy
- Wind - 221115
    + wind energy
- Geothermal - 221116
    + geothermal energy

The first 4 of those should add up to NAICS code 21.

------

The headings in this section can be:

- Wage and salary jobs
   - Extractive industry jobs
   - Extractive industry jobs by county
      - Jobs by industry sector

------

The sentences below the 10-year sector graphs should read:

- In 2015, there were 10,490 [oil and gas extraction] jobs in California.
- In 2015, there were 10,490 [coal extraction] jobs in California.
- In 2015, there were 10,490 [nonenergy mineral extraction] jobs in California.
- In 2015, there were 10,490 [mining support] jobs in California.
- In 2015, there were 10,490 [solar energy] jobs in California.
- In 2015, there were 10,490 [wind energy] jobs in California.
- In 2015, there were 10,490 [geothermal energy] jobs in California.

**Comment by coreycaitlin** [comment]
New option for commodity breakdowns that lump in "mining support" with the relevant commodity instead of keeping it separate:

- Oil & gas - NAICS 211 + 213111 + 213112
    + oil and gas extraction
- Coal - NAICS 2121 + 213113
    + coal extraction
- Nonenergy minerals - 2122 + 2123 + 213114 +213115
    + nonenergy mineral extraction
- Solar - 221114
    + solar energy
- Wind - 221115
    + wind energy
- Geothermal - 221116
    + geothermal energy

**Comment by gemfarmer** [comment]
https://gsa-tts.slack.com/archives/C02D904LA/p1495727949887270

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] Update the documentation and/or wiki data notes to note the NAICS code groupings/mapping
- [ ] Add link to energy jobs report
- [ ] Add note about scope of renewable jobs data
- [ ] Open issues for additional jobs/compensation data we want to incorporate in the future

**Comment by gemfarmer** [comment]
Thanks for the detailed notes, @shawnbot. Hopefully I'll have time to wrap this issue up soon. Looks like great work :)

**Comment by coreycaitlin** [comment]
See #2311 and #2312 for future additions to jobs data.

**Comment by gemfarmer** [comment]
@coreycaitlin @shawnbot do we want to include Puerto Rico in this data set?

**Comment by gemfarmer** [comment]
@coreycaitlin I didn't make any changes to the datasets, but I'm pretty low on time these days, and after the changes I made (removing Puerto Rico and Virgin Islands) I think this data looks good! ✅

**Comment by coreycaitlin** [comment]
@gemfarmer thanks! Weirdly, the right-hand sub-nav items aren't showing up for me on these previews. Maybe we could take a look together later this week?

**Comment by gemfarmer** [comment]
@coreycaitlin strange. Just checked and they are showing up for me. Looking at it later in the week would be good. Does the EITI slot tomorrow work?

**Comment by coreycaitlin** [comment]
Sounds like we now have 2016 data! Let's pair on getting that added before we launch this, if possible.

**Comment by gemfarmer** [comment]
This is the PR that keeps on giving. Looking forward to settling it this afternoon

**Comment by coreycaitlin** [comment]
This now includes 2016 data, but still has a buggy sidenav issue. Getting closer!

**Comment by gemfarmer** [comment]
@coreycaitlin 
Re-webpacked the JS and changed the JS to not build empty sparkbars. I also added sparkbars for jobs by commodity!

**Comment by coreycaitlin** [comment]
Looks good! I think this is just waiting for Chris's review now. We can also merge and do that review on dev.

**Comment by gemfarmer** [comment]
@coreycaitlin which would you rather do. I'm tempted to hit the green button...

**Pull request merged**
