### PR TITLE
Fix styleguide

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes #667 

These changes should work, but I can't view the [preview link](https://federalist.18f.gov/preview/18F/doi-extractives-data/fix-styleguide/) @shawnbot @meiqimichelle any suggestions for why I wouldn't be able to view a federalist branch?

screen shot 2015-10-26 at 4 32 26 pm

### CODE REVIEW

**Comment by meiqimichelle** [comment]
Another `disk quota error` :sob:

**Comment by gemfarmer** [comment]
:sob: no! I tried deleting unnecessary remote branches. Maybe that will help?

**Comment by meiqimichelle** [comment]
The Federalist team increased our quota, we should be good. Or rather -- errors now are not because of the disk quota :trollface:

**Comment by gemfarmer** [comment]
So I'm not sure why I didn't think of this before, but I'm pretty sure that the issue is that the npm task is never triggered by the jekyll build. Looking into ways to configure jekyll to accept alternative default build commands. @shawnbot do you have any experience doing this?

**Comment by gemfarmer** [comment]
Actually, scratch that. I doubt that is the issue because stylguide is already in the `_site` directory

**Comment by gemfarmer** [comment]
Actually, I think I just needed a less compiler for the site to generate kss.css

**Comment by gemfarmer** [comment]
Ah! it was a .gitignore issue. This PR should fix the issue we were having with the missing styleguide kss.css!

**Comment by meiqimichelle** [comment]
Looks good now! :mouse: :boom:

**Pull request merged**
