### PR TITLE
Updated color palette

### LINKED ISSUE #1247: Palette tweaks
@gemfarmer A few minor adjustments to the colors, which will primarily impact the "hero" spaces atop the home page, and the landing pp for About, How it works, and Explore data...

 - [x] Update the blues:

   - $blue stays the same (#157bac)
   - [x] $light-blue (currently #e6f9ff): change to #e3f8ff
   - [x] $pale-blue (currently #f2fcff): change to #f0fcff
   - [x] $mid-blue (currently #c6e9ff): change to #c9eeff

 - [ ] Two other color issues:
   - [ ] $light-gray (#f7f7f7): are we using anywhere?
   - [x] $shock-green (#acb626): this should go away altogether. I see it in some icons at the bottom of diving graphics pp. (Those can all be changed to $blue.) Is it anywhere else that you know of?

thx!

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes #1247 

[Preview](https://federalist.18f.gov/preview/18F/doi-extractives-data/palette-tweaks/)

@ericronne I have replaced all of the colors _except_ `$light-gray`. 
[See my comments](https://github.com/18F/doi-extractives-data/issues/1247#issuecomment-180033220) to see if we should remove it, and if so what we should replace it with.

### CODE REVIEW

**Comment by ericronne** [comment]
Let's hold off on the gray for now. I'll make a new issue later if i think it should be changed. :)

**Comment by gemfarmer** [comment]
@ericronne Is this merge-able then?

**Comment by ericronne** [comment]
Not sure how i confirm all of the hex values :/

**Comment by gemfarmer** [comment]
Hmmm. Yeah, they appear all over the place. The colors are all changed, the real question here in my mind is, do those color decisions look good site-wide? I'm less clear on this. We could merge and as/if instances of those colors **not** looking ideal show up, we could fix them individually. None of the color changes are drastic enough to _break_ something stylistically, imho.

**Comment by ericronne** [comment]
I think all the blues are groovy.

Do i need to provide an updated gif for the home page?

As much as i hate to create unique instances, if we could change **only** the gray on the bottom of the home page to `#f2f2f2`, i think that might be a nice bump in contrast, to help those cards to emerge. Doable?

**Comment by gemfarmer** [comment]
@ericronne yes that is doable

**Comment by ericronne** [comment]
Cool, go for it? :+1:

**Comment by gemfarmer** [comment]
@ericronne Ok. Finally changed this gray. The colors should be what you ordered. ;)

What gif were you talking about above?

**Comment by ericronne** [comment]
image

**Comment by gemfarmer** [comment]
Ah! Let's add this to the new bug branch you just made.

**Pull request merged**
