### PR TITLE
Content audit edits and link fixes

### PR DESCRIPTION
**Pull request by brentryanjohnson**
Related to #2624 

This is an ongoing content audit. We should merge in the changes each week to avoid a pile-up!

[:sunglasses: PREVIEW](https://federalist.fr.cloud.gov/preview/18f/doi-extractives-data/content-audit-edits/)

### CODE REVIEW

**Comment by coreycaitlin** [comment]
@brentryanjohnson Is this good to review/merge by the end of today?

**Comment by brentryanjohnson** [comment]
@coreycaitlin Yes!

**Comment by coreycaitlin** [comment]
@brentryanjohnson just let me know if you want me to review now, or wait for any final bits you wanna check in!

**Comment by brentryanjohnson** [comment]
@coreycaitlin I'm going to keep chipping away at it, so now is as good a time as any!

**Pull request merged**
