### PR TITLE
Layout refinements

### PR DESCRIPTION
**Pull request by gemfarmer**
Fixes issue(s) #1597 

[:sunglasses: PREVIEW](https://federalist.18f.gov/preview/18F/doi-extractives-data/layout-refinements/states/)

Changes proposed in this pull request:

- [x] improve `.chart-title` vertical alignment
- [x] added extent line with units and SI units to _all_ bar charts
- [x] removed period from bar chart sentence.
- [x] improved spacing between bars and words
- [x] per @ericronne's suggestion, made Production an h2 heading and added a subheading for all production
- [x] made font and spacing changes per Eric's suggestions

screen shot 2016-07-29 at 11 46 45 am

/cc @ericronne @meiqimichelle

### CODE REVIEW

**Comment by ericronne** [comment]
@gemfarmer Super close! 😁  
Just a couple of fine-tuning adjustments would make it perfect. Do you want to do a quick live-vizbug squash session?

**Comment by gemfarmer** [comment]
I'll DM you to schedule the vizbug session

**Comment by gemfarmer** [comment]
- [ ] make vertical spacing on `chart-title` bigger

**Comment by ericronne** [comment]
@gemfarmer you mean smaller? 😬 
Leading of chart titles is currently a little generous.

**Comment by gemfarmer** [comment]
@ericronne yes, smaller. Edited.

**Comment by ericronne** [comment]
- [ ] Reduce vertical spacing between the summary sentence and the Y axis dotted line
Ideal > image

 - [ ] Add vertical spacing between the bottoms of the bars and the years (match the spacing we have for leading between the years and the word "YEARS"
Ideal > image

 - [ ] Investigate rounding to one significant figure, so the Y axis line doesn't hit the tops of the highest bars

 - [ ] If it's possible for the bars to go all of the way to the right and left edges of the charts, that would be great. If not, it's ok for the bottom line rule to hang a little, as it currently does.

**Comment by gemfarmer** [comment]
@ericronne I couldn't easily stretch the bar to the end of the chart. Ready for review. Feel free to merge if you like!

**Comment by gemfarmer** [comment]
Also, ignore all the `Avoid vendor prefix` flags. I want to avoid them, but I'm pretty sure we have to use them if we want this layout to work cross browser.

@shawnbot ?

**Comment by gemfarmer** [comment]
Nevermind:

> Method of positioning elements in horizontal or vertical stacks. Support includes the support for the all properties prefixed with flex as well as display: flex, display: inline-flex, align-content, align-items, align-self, justify-content and order.

**Comment by gemfarmer** [comment]
@ericronne the text height still hasn't been dealt with. I have made a spillover issue [here](https://github.com/18F/doi-extractives-data/issues/1700)

**Pull request merged**
