### PR TITLE
Explore > Federal Production

### PR DESCRIPTION
**Pull request by shawnbot**
This PR gets the Explore Data > Federal Production section up and running, recycling much of the code from the Revenue section. You can preview it on Federalist here:

https://federalist.18f.gov/preview/18F/doi-extractives-data/explore-production/explore/federal-production/

There are a couple of issues to work out before review and merging:

- [x] aggregating the product counts at the overall and subregion levels is busted
- [x] the bar charts shouldn't show up when we're listing product counts, per #679 
- [x] the timeline and map should display "binary" product counts, rather than with a linear scale (solution: modify the scale if a product isn't selected)
- [x] wording in dynamic headings should follow Nicole's recommendation in #772

I've also included a bunch of fixes for the Explore > Federal Revenue section as I made similar fixes and adjustments in this section.

### CODE REVIEW

**Comment by meiqimichelle** [comment]
@shawnbot There might be something wrong with hardrock minerals -- I'm not getting any production numbers:

screenshot 2015-11-19 23 28 09

**Comment by meiqimichelle** [comment]
Aaaahhh, I'm slowly figuring this out -- there's something happening with the `commodity` versus `product` options. When `commodity` shows up, things get wierd. See also -- this list is missing gold:

screenshot 2015-11-19 23 32 49

**Comment by meiqimichelle** [comment]
Final note of the night -- how many products are there? I think the most useful bit of those drop-downs is the big list so you can see all the options and what they're measured in.  Can do just that, or just one top-level grouping plus all the products associated with it?

**Comment by gemfarmer** [comment]
Just added some of my own changes to the branch. Conflict free!

**Comment by usEITI** [comment]
I checked the CY production for federal and gold data is always withheld
because potential impact of the Trade Secrets Act.

On Fri, Nov 20, 2015 at 11:42 AM, Shawn Allen <notifications@github.com>
wrote:

> Yeah that might be a good call, @mieqimichelle. We could just turn it into
> one big drop-down for all the products. Maybe fancy auto-complete later?
>
> If gold isn't showing up, it could be that it's not present in the data.
> Because that product list is generated from the data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/doi-extractives-data/pull/807#issuecomment-158454556>
> .
>



-- 
*Judy Wilson*
*Program Manager USEITI Secretariat *
*Office of Natural Resources Revenue*

*judith.wilson@onrr.gov <judith.wilson@onrr.gov>*
*202-208-4410*

**Pull request merged**
